### ISSUE TITLE
--remove-v1 also clears ID3V2 tag on some files on v0.8.2

### ISSUE THREAD

**Issue by core-code** [nicfit/eyeD3#102]
the documentation implies
eyeD3 --remove-v1 FILE.MP3
only removes the id3v1 tag but leaves the id3v2 tag intact.

however for some files the id3v2 tag is totally cleared as well. (can send sample files)

i just lost tags for 10.000+ mp3s because of this malfunction

**Comment by nicfit** [comment]
Please tar/zip some examples to reproduce and attach, I have not reproduced this yet.

**Comment by core-code** [comment]
currently looking for files to reproduce it ... need to consult the backups.

however its easy to reproduce when combining with the "--to-v2.4" option ... take any file that has both id3v1 and v2 tags, then do

eyeD3 --to-v2.4 --remove-v1 test.mp3 

bam, v1 gone (as its supposed to be) but the v2 tags empty

**Comment by nicfit** [comment]
https://github.com/nicfit/eyeD3/pull/103 is meant to address this. Test if you can.

**Comment by core-code** [comment]
ok there seem to be two separate problems i both have run into.

first one, if you combine "--remove-v1" with "--to-v2.4" (or --to-v2.3 i guess), then the v2 tag will be wiped clean. i can confirm that pull request 103 fixes this issue. thanks for the prompt fix!


the second issue i encountered is that "--remove-v1" will not update the v2 tag when some values are missing.
for example, suppose you have a MP3 that has both v1 and v2 tags, as is common. if one of the tags (e.g. artist) is missing in the v2 tag, you will normally never notice because common music players like iTunes will fall back to using the v1 tag for (just) this tag.
however, if you remove the v1 tag with "--remove-v1", the missing value will not be pulled from the v1 tag like music players do it. the v1 tag will just be removed without the v2 tag being updated. so you suddenly have incomplete tags.
i propose that "--remove-v1" will update the v2 header in case that values are missing that are present in the v1 header. this will ensure no data loss can happen.

**Comment by nicfit** [comment]
Remove options will not copy data, or ensure matches between tag versions. Scripts can/should do that separately from the remove.

**Comment by core-code** [comment]
ok. please update the documentation though to inform that this can lead to data loss
