### ISSUE TITLE
some files are ignored with "Nothing to do"

### ISSUE THREAD

**Issue by core-code** [nicfit/eyeD3#104]
eyeD3 0.8.2 is unable to display any tags on some of my files. 
trying "eyeD3 -1" or "eyeD3" on them just displays:
Nothing to do

happy to send some 'offending' files by mail

**Comment by nicfit** [comment]
There is nothing to do if the data is not mp3. Using your samples.

```bash
$ file bug_104.mp3 
bug_104.mp3: Audio file with ID3 version 2.4.0, contains:dBase IV DBT of \340.DBF, blocks size 0, block length 13312, next free block index 7, next free block 2670699393, next used block 806749232
```
and eyeD3's mime-type is: eyed3.core:DEBUG: File mime-type: application/x-dbt

**Comment by core-code** [comment]
according to iTunes, QuickTime, VLC, mplayer & mp3val this is a valid MP3 and i can see the ID3 tags in the hex editor, but you are the expert. i'll get a fresh copy of 'affected files'.
