### ISSUE TITLE
pip/pip3 install eyeD3 doesn't install grako automatically

### ISSUE THREAD

**Issue by marcelpaulo** [nicfit/eyeD3#115]
Trying to run eyeD3 right after install (both python2 and python3), it complains of missing **grako**:

```
Unknown module 'grako'
Please install grako! E.g. with $ pip install grako
```

Of course, I then installed it, but shouldn't it be installed automatically, as a dependency, like pathlib, python-magic and six ?

**Comment by nicfit** [comment]
This is meant to be opitonal, the following will get you grako:
```
pip install eyeD3[display-plugin]
```
But, the output you see about installing grako is not ideal, and I'd like fix. Note, eyeD3 still appears to work depsite the noise.

**Comment by marcelpaulo** [comment]
Hey, thanks for clarifying, @nicfit. I've just tried it: uninstalled _grako_ and I can still run eyeD3 with the basic plugin. Indeed it would be cleaner to show the message only when trying to use the display plugin.

**EDIT:** I forgot to mention: eyeD3 is **THE** command line tool to work with mp3 ID3 tags, no other tool gets near it in flexibility and usefulness. eyeD3 + puddletag + mp3diags = holy trinity to work with mp3 files !

**Comment by marcelpaulo** [comment]
Just tested it, working flawlessly. Thanks !
