### ISSUE TITLE
ID3 tag TCOM (composer) not handled by plugins classic and display

### ISSUE THREAD

**Issue by marcelpaulo** [nicfit/eyeD3#116]
Plugins **classic** and **display** don't handle ID3 tag **TCOM** (composer).

Any particular reason for leaving it out ? Will it be handled in the future ?

**Comment by nicfit** [comment]
No reason other then it's not done yet.

**Comment by marcelpaulo** [comment]
Thanks. I have tons of classical music CDs in my mp3 collection, so I tend to use TCOM quite a lot, that's why I asked.

**Comment by nicfit** [comment]
Totally understand.

**Comment by nicfit** [comment]
Fixed by https://github.com/nicfit/eyeD3/pull/123

**Comment by marcelpaulo** [comment]
Have just downloaded the latest commits, it's working flawlessly ! Thank you so much, @nicfit !
