### ISSUE TITLE
no need for ord() on Python 3

### ISSUE THREAD

**Issue by ewerybody** [nicfit/eyeD3#12]
Seems [this](https://github.com/nicfit/eyeD3/blob/master/src/eyed3/mp3/headers.py#L314) always breaks for me on Python 3! How do you work with that? I never get it to work. Only in Python 2.7x

This line gets an index from a bytes object and is already the integer then. Asking it for ord() breaks:
```
  File "C:\Python36\lib\site-packages\eyed3\mp3\headers.py", line 311, in decode
    version = (ord(frame[1]) >> 3) & 0x1
TypeError: ord() expected string of length 1, but int found
```

Apperently its a Python 3 feature. We could implement something like
```
def _ordinal(one_char_string):
    if isinstance(one_char_string, int):
        return one_char_string
    else:
        return ord(one_char_string)
```
But maybe this should be just different code when got from pip for Python 3 like?:
```
    def decode(self, frame):
        # mp3 version
        version = (_frame[1] >> 3) & 0x1
```
But wait a second... It doesn't even work then! Doesn't even complain! `.tag` is of type `None` then.
Aaaahhhh! Is this something that release 0.8.0 is fixing!? When will it be in?

**Comment by nicfit** [comment]
version = (compat.byteOrd(frame[1]) >> 3) & 0x1  

This is solved in the compat module which does essentially that _ordinal function. It has been python3 compatible for a  while now. The beta of 0.8.0 is on PyPI (and current master branch in git), check it outif you can. I'm sure there are still bytes/unicode issues lurking.

**Comment by ewerybody** [comment]
Yea I got me the 0.8.0 and it worked! Thanks!
I got something like these bytes/unicode issues tho. But couldn't repro again.

I wonder how could 0.7.x get to Python 3.x with this?
Still if you just `pip install eyed3` on Python 3.x you can't `load()` an mp3.

**Comment by nicfit** [comment]
0.7.x is not Py3 compatible. That's what 0.8 will be.

**Comment by ewerybody** [comment]
But shouldn't that be something that you are made aware of when getting it through pip? Like PySide does for instance? 
![screen_80](https://cloud.githubusercontent.com/assets/218956/23471710/89a88bf6-feaa-11e6-9c81-847976b390ba.png)

**Comment by nicfit** [comment]
Hmm, not sure how that is done. Check out the 0.7 PKGINFO on PYPI, I thought those classifiers would come into play here:
https://pypi.python.org/pypi?name=eyeD3&version=0.7.10&:action=display_pkginfo
