### ISSUE TITLE
MagicException(err) on import eyed3

### ISSUE THREAD

**Issue by damihm** [nicfit/eyeD3#132]
Python v3.7.0a3 , eyed3 v0.8.4 , python_magic v0.4.15 ,
os Windows 7 , and x64 dll's from libmagicwin64-master (files timestamped 2015).

import magic returns no error, but upon import eyed3, the following is output (in IDLE):

Traceback (most recent call last):
  File "<pyshell#123>", line 1, in <module>
    import eyed3
  File "D:\Python\Python3\lib\site-packages\eyed3\__init__.py", line 36, in <module>
    from .core import load                                                # noqa
  File "D:\Python\Python3\lib\site-packages\eyed3\core.py", line 9, in <module>
    from .utils import guessMimetype
  File "D:\Python\Python3\lib\site-packages\eyed3\utils\__init__.py", line 53, in <module>
    _mime_types = MagicTypes()
  File "D:\Python\Python3\lib\site-packages\eyed3\utils\__init__.py", line 41, in __init__
    keep_going=False)
  File "D:\Python\Python3\lib\site-packages\magic.py", line 67, in __init__
    magic_load(self.cookie, magic_file)
  File "D:\Python\Python3\lib\site-packages\magic.py", line 264, in magic_load
    return _magic_load(cookie, coerce_filename(filename))
  File "D:\Python\Python3\lib\site-packages\magic.py", line 195, in errorcheck_negative_one
    raise MagicException(err)
magic.MagicException: None
[end output]

Very interested in adding this to my mp3 scripting flow; hopefully, we can get this to work. Yes, I know the documents indicate python >=3.3, but I can hope can't I?

Thanks!

**Comment by 1deterministic** [comment]
I just started to use eye3D today and I faced the same error. What I did was to download the zip from GitHub and install it manually, instead of using pip install. Maybe it will work for you as well!

**Comment by damihm** [comment]
No luck, same errors.

**Comment by MitchProbst** [comment]
I'm having the same issue using Python 3.6.3, eyed3 0.8.4, the x64 dll's installed from https://github.com/pidydx/libmagicwin64 as suggested on Windows 10. I tried the suggestion given by @1Deterministic and was still unable to resolve the issue.

**Comment by 1deterministic** [comment]
Sorry guys, I tried to setup again on a clean Windows install on a VM and what seems to have worked actually was to install the .whl file from [https://pypi.python.org/pypi/python-magic-bin/0.4.14](https://pypi.python.org/pypi/python-magic-bin/0.4.14). I choosed the file based on Python architecture rather than the OS and installed with `pip install whateverfilewasdownloaded.whl`. Could someone try it to confirm?

**Comment by simonfranz** [comment]
I had the same error.
thanks @1Deterministic, Installing the "python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl" fixed my issue now it works. Thanks!

**Comment by 1deterministic** [comment]
Great, @simonfranz! Glad to see that it worked, hopefully it will help more people with the same problem.

**Comment by copeland3300** [comment]
Thanks to @simonfranz for his info. 

Fixed on Windows 10 x64 Build 1803 with 
```
pip install python-magic-bin
```
