### ISSUE TITLE
dangerous auto-recursive

### ISSUE THREAD

**Issue by Bahram-Alinezhad** [nicfit/eyeD3#133]
When applying eyeD3 to a folder without any switch, it finds and acts recursively on all subfolders and files, which is not normally expected and may lead to unwanted results specially when used with --remove switch. I suggest make a -r or -R switch mandatory for this type of action.

**Comment by davebiffuk** [comment]
Seconded. I accidentally typed `eyed3 --remove-all *mp3` instead of `eyed3 --remove-all *.mp3` and eyeD3 started to recurse down my `mp3` folder. I was able to ctrl-C it after it had stripped tags from only two files, but it would be great to have a safety net around acting on directories.

**Comment by nicfit** [comment]
I started a branch for this experiment.  https://github.com/nicfit/eyeD3/tree/default-recursion
