### ISSUE TITLE
configure; make; make install

### ISSUE THREAD

**Issue by Bahram-Alinezhad** [nicfit/eyeD3#134]
Please make it again available compiling the project by "configure; make; make install".

**Comment by nicfit** [comment]
Sorry, there is no good reason to use autoconf for this project. Why is it necessary for your workflow?

**Comment by Bahram-Alinezhad** [comment]
Hello

You might leaved autoconf for either of these reasons:
1- There are technical reasons that autoconf was good in past but is not good already and there are difficulties for maintaining it.
2- You may believe python is easier and there are no more users who prefer autoconf.

If the former is false and later is true, FYI, I couldn't install it because my python version is 2.6. Also I prefer autoconf as it is the standard way of compiling most linux packages. Else, OK to close the issue "wontfix". Thank you for your response and discussion.

**Comment by Bahram-Alinezhad** [comment]
Hello

You might leaved autoconf for either of these reasons:
1- There are technical reasons that autoconf was good in past but is not good already and there are difficulties for maintaining it.
2- You may believe python is easier and there are no more users who prefer autoconf.

If the former is false and later is true, FYI, I couldn't install it because my python version is 2.6. Also I prefer autoconf as it is the standard way of compiling most linux packages. Else, OK to close the issue "wontfix". Thank you for your response and discussion.

**Comment by Bahram-Alinezhad** [comment]
Hello

You might leaved autoconf for either of these reasons:
1- There are technical reasons that autoconf was good in past but is not good already and there are difficulties for maintaining it.
2- You may believe python is easier and there are no more users who prefer autoconf.

If the former is false and later is true, FYI, I couldn't install it because my python version is 2.6. Also I prefer autoconf as it is the standard way of compiling most linux packages. Else, OK to close the issue "wontfix". Thank you for your response and discussion.

**Comment by Bahram-Alinezhad** [comment]
Hello

You might leaved autoconf for either of these reasons:
1- There are technical reasons that autoconf was good in past but is not good already and there are difficulties for maintaining it.
2- You may believe python is easier and there are no more users who prefer autoconf.

If the former is false and later is true, FYI, I couldn't install it because my python version is 2.6. Also I prefer autoconf as it is the standard way of compiling most linux packages. Else, OK to close the issue "wontfix". Thank you for your response and discussion.
