### ISSUE TITLE
Traceback issue?

### ISSUE THREAD

**Issue by Sirove** [nicfit/eyeD3#151]
I'm using Python 3.6.4 on Windows 10 (x64) and installed eyeD3 via pip as mentioned in the documentation: `pip install eyeD3`. It worked but when I type any command with eyeD3 this happens:

> Traceback (most recent call last):
>   File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\python36\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Python36\Scripts\eyeD3.exe\__main__.py", line 5, in <module>
>   File "c:\python36\lib\site-packages\eyed3\__init__.py", line 35, in <module>
>     from .utils.log import log                                            # noqa
>   File "c:\python36\lib\site-packages\eyed3\utils\__init__.py", line 27, in <module>
>     import magic
>   File "c:\python36\lib\site-packages\magic.py", line 181, in <module>
>     raise ImportError('failed to find libmagic.  Check your installation')
> ImportError: failed to find libmagic.  Check your installation

So I did: `pip install libmagic` but it seems to be already installed: 

> Requirement already satisfied: libmagic in c:\python36\lib\site-packages

What is the problem?

**Comment by nicfit** [comment]
Check out [this issue](https://github.com/nicfit/eyeD3/issues/89) @Sirove . It should help.
