### ISSUE TITLE
sooooo  many error in running tests

### ISSUE THREAD

**Issue by themaddoctor** [nicfit/eyeD3#156]
So many tests fail. Many because src/test/data and the files that the tests look for in that directory are missing.

Also, DisplayPatternParser is not defined. What is that?

**Comment by nicfit** [comment]
Hi @themaddoctor , 
Latest test results can be found [here](https://travis-ci.org/nicfit/eyeD3)

Most likely you are missing deps and data. The tests will run and skip tests that require data, but it's good to have them all run, esp. if hacking.  I've made a quick [update](https://github.com/nicfit/eyeD3/commit/1b22d87b9707bb8a1bdbc7da166bec33e10e6e7b) to the docs to help with this. Let me know how that goes.
