### ISSUE TITLE
python3 setup.py install --user pulls python 2.7 version of six, pathlib and python-magic

### ISSUE THREAD

**Issue by marcelpaulo** [nicfit/eyeD3#160]
Installing eyeD3 with `python3 setup.py install --user` pulls python 2.7 version of these dependencies:

```
six
pathlib
python-magic
```

so eyeD3 can't find them:

```
paulo@monk:~/src/eyeD3$ eyeD3 ~/stage/cd/
Traceback (most recent call last):
  File "/home/paulo/.local/bin/eyeD3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-magic' distribution was not found and is required by eyeD3
```

Installed version of eyeD3: 95fd20778524007c1a46d5ad62ff6327a912c38a
Environment: Xubuntu 17.10

I should mention: python's default version in Xubuntu 17.10 is **2.7.14**

**Comment by marcelpaulo** [comment]
I think I spotted the problem but I don't know python to be able to fix it: `setup.py` calls `pip` to install the requirements, and `pip` in Xubuntu 17.10 is python2:

```
paulo@monk:~/src/eyeD3$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

I also installed _subliminal_  and _guessit_ from source also using `python3 setup.py install --user`, and they pulled the python3 requirements. I looked at their `setup.py` but don't know Python enough to be able to decypher how they do it right.

As a workaround, of course, I installed python2 eyeD3 with `python setup.py install --user`

**Comment by marcelpaulo** [comment]
Oh dear, workaround doesn't quite work because python2 eyeD3 has this problem:

```
Uncaught exception: 'ascii' codec can't encode character u'\xba' in position 8: ordinal not in range(128)
```

So the real workaround will be to install the dependencies from the Ubuntu repositories or `pip3 install` them **BEFORE** installing eyeD3

**Comment by marcelpaulo** [comment]
Even running:

`pip3 install python-magic pathlib six grako`

**BEFORE** running:

`python3 setup.py  install --user`

The python2 versions of the dependencies are still being installed.

**Comment by nicfit** [comment]
I suspect these test are not happening within a Python3 virtualenv, where `pip` would be `pip3`. Can you confirm?

Also, the test results using the following change would be interesting.

```diff
diff --git a/setup.py b/setup.py
index 0540a46..4902349 100755
--- a/setup.py
+++ b/setup.py
@@ -100,7 +100,7 @@ def requirements_yaml():
 class PipInstallCommand(install, object):
     def run(self):
         reqs = " ".join(["'%s'" % r for r in PKG_INFO["install_requires"]])
-        os.system("pip install " + reqs)
+        os.system("pip3 install " + reqs)
         # XXX: py27 compatible
         return super(PipInstallCommand, self).run()
```

**Comment by marcelpaulo** [comment]
You're right on the spot with both alternatives, @nicfit, both work as you expected ! Thanks for that !

**Comment by marcelpaulo** [comment]
I recently installed Xubuntu 18.04 afresh, so had to reinstall eyeD3 and got caught again in this issue because python2 is still the default python, even though Ubuntu 18.04 adopted python3 as the default.

A thought: wouldn't it be the case of _setup.py_ checking the current default python version and use **pip** if the default is python3, and **pip3** if the default is python2 ?
