### ISSUE TITLE
latin-1 can't write a special character to the tag

### ISSUE THREAD

**Issue by hollysheep** [nicfit/eyeD3#165]
Hi,

i use eyeD3 to write the file name as title tag to the mp3 file. the file is downloaded with my podcast tool and can't be renamed because the tool will download the file again. i use this simple script

```
for i in /home/username/podcast/*.mp3 ; do
title=$(basename "$i" .mp3)
eyeD3 -t "$title" "$1"_new.mp3
done
```

the error i have at the moment is

```
Uncaught exception: 'latin-1' codec can't encode character u'\u2013' in position 25: ordinal not in range(256)
Traceback (most recent call last):
  File "/usr/bin/eyeD3", line 1265, in <module>
    retval = main();
  File "/usr/bin/eyeD3", line 1242, in main
    retval = app.handleFile(f);
  File "/usr/bin/eyeD3", line 559, in handleFile
    if not self.tag.update():
  File "/usr/lib/python2.7/dist-packages/eyeD3/tag.py", line 526, in update
    self.__saveV2Tag(version);
  File "/usr/lib/python2.7/dist-packages/eyeD3/tag.py", line 1251, in __saveV2Tag
    raw_frame = f.render();
  File "/usr/lib/python2.7/dist-packages/eyeD3/frames.py", line 756, in render
    self.text.encode(id3EncodingToString(self.encoding));
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2013' in position 25: ordinal not in range(256)
```
the characters is a "–". thats no a normal "-". when i change it the script works. is this a problemwith eyed3 or do i need to change something in the script?

**Comment by nicfit** [comment]
Encoding matters within the tag values, and for the filenames, and each is tweaked differently. From the looks of things the problem is in a tag value, and "–" is not a valid latin1 character. You need to select a diffrerent encoding and the valid choices are all dependent on tag version (e.g. unicode is not acceptable at all in v1.x ID3 tags). Converting the tag to a modern version and/or selecting a acceptable encoding is should work. 

```bash
$ eyeD3 --encoding utf8 --to-v2.4  --title foo–bazz test.id3 
```

**Comment by hollysheep** [comment]
This is strange. Now i've the Error

> eyeD3: error: no such option: --encoding

I've installed eyeD3 from the Ubuntu repository.

**Comment by nicfit** [comment]
What's the version? What does --help say?

**Comment by hollysheep** [comment]
Works with "--set-encoding utf8".

Thanks.
