### ISSUE TITLE
eyeD3 chokes if file path contains non-ascii Unicode characters

### ISSUE THREAD

**Issue by jimav** [nicfit/eyeD3#169]
Using eyeD3 version 0.8 on Ubuntu 17.10, which has python 2.7.14 

If the .mp3 file name, or any ancestor directory, contains a non-ascii Unicode character, then eyeD3 gets an exception and aborts.

This effectively requires Album and Song titles to be written only in English!

STEPS TO REPRODUCE:

    export LANG=en_US.UTF-8 
    cp anysong.mp3 Странджанска.mp3
    eyeD3 --add-image anyimage.jpg:FRONT_COVER Странджанска.mp3

(Adding `--encoding=utf8` makes no difference)

RESULTS:

<pre>
Uncaught exception: 'ascii' codec can't encode characters in position 5-16: ordinal not in range(128)

eyed3:ERROR: 'ascii' codec can't encode characters in position 5-16: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/eyed3/main.py", line 279, in _main
    retval = mainFunc(args, config)
  File "/usr/lib/python2.7/dist-packages/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/usr/lib/python2.7/dist-packages/eyed3/utils/__init__.py", line 81, in walk
    handler.handleFile(os.path.abspath(path))
  File "/usr/lib/python2.7/dist-packages/eyed3/plugins/classic.py", line 457, in handleFile
    super(ClassicPlugin, self).handleFile(f, tag_version=parse_version)
  File "/usr/lib/python2.7/dist-packages/eyed3/plugins/__init__.py", line 172, in handleFile
    self.audio_file = core.load(f, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/eyed3/core.py", line 77, in load
    path = pathlib.Path(path)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 936, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 613, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 606, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 75, in parse_parts
    parts = _py2_fsencode(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 58, in _py2_fsencode
    else part for part in parts]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-16: ordinal not in range(128)
</pre>

**Comment by nicfit** [comment]
If the filesystem encoding matches the encodng used for those filenames then this does not happen.

**Comment by jimav** [comment]
nicfit: Could you be more specific?  What are the exact options or environment variables needed to make UTF-8 encoded filenames work?

I tried `LANG=en_US.UTF-8 eyeD3 --fs-encoding=utf-8 --encoding=utf8 --add-image good.jpg:FRONT_COVER Странджанска.mp3` and got the same crash.

I'm pretty certain the actual file system is not corrupting anything, as the UTF-8 encoded characters are coming out of "readdir" as expected.  I don't know Python, but this Perl script decodes file names expecting UTF-8 and finds no errors, and the decoded-to-perl-internal-representation results display correctly (after being re-encoded to UTF-8 and written to stdout, which is connected to a utf-8-enabled gnome-terminal): 
<pre>
perl -COE -MEncode -E 'opendir DIR,"." or die; say $_ foreach( grep{/mp3$/}map{decode("UTF-8",$_,Encode::FB_CROAK)} readdir DIR )'
</pre>

**Comment by nicfit** [comment]
Can you try with the latest version of eyeD3 (0.8.4)? I did a quick test with python3 and python2.7:
This may be releated to #56.

```
$ cp ./test.mp3 Странджанска.mp3
$ eyeD3 -a test Странджанска.mp3
$ eyeD3 Странджанска.mp3
$  locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

You might also notice, the error is originating in Python Path class, which is add-on for Python2.7, I'm curious how/if Python3 is different.

**Comment by jimav** [comment]
0.8 won't work with python 3.6.3 (at least by just running `python3 /usr/bin/eyeD3 ...`). 

It chokes on the `__requires__ = 'eyeD3==0.8'` at the top of the file, with an exception ending with "pkg_resources.DistributionNotFound: The 'eyeD3==0.8' distribution was not found and is required by the application".

Anyway, this does sound like exactly the same as issue https://github.com/nicfit/eyeD3/issues/56

which is a very serious problem for many of us.  

I don't have access to 0.8.4 (that I know of), so haven't tried it.

**Comment by jimav** [comment]
Ok, I found 0.8.4 in the future Ubuntu 18.04 ("Bionic") beta, and it does not have the problem any more.

Thanks, I'll have to upgrade sooner or later.

(Sorry, I accidentally closed this issue - clicked the wrong button.  But it looks to be resolved so I'm guessing closing it is okay)

**Comment by jimav** [comment]
For anyone on Ubuntu 17.10 or earlier, this worked for me:

1. Temporarily added the following lines to /etc/apt/sources.list : 

    deb http://us.archive.ubuntu.com/ubuntu/ bionic universe
    deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe

2. sudo apt-get update
3. sudo apt-get install eyed3 (installs version 0.8.4 which fixes the bug)
4. Remove (or comment out) the lines added to /etc/apt/sources.list
5. sudo apt-get update
