### ISSUE TITLE
Traceback when trying to output images tag

### ISSUE THREAD

**Issue by konomikitten** [nicfit/eyeD3#176]
I'm running the following command: `eyeD3 --plugin=display --pattern '%images%' [FILE]` and getting this outout:

> Uncaught exception: 'int' object has no attribute 'join'
> 
> eyed3:ERROR: 'int' object has no attribute 'join'
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/eyed3/main.py", line 277, in _main
>     retval = mainFunc(args, config)
>   File "/usr/local/lib/python2.7/dist-packages/eyed3/main.py", line 50, in main
>     fs_encoding=args.fs_encoding)
>   File "/usr/local/lib/python2.7/dist-packages/eyed3/utils/__init__.py", line 95, in walk
>     handler.handleFile(os.path.abspath(path))
>   File "/usr/local/lib/python2.7/dist-packages/eyed3/plugins/display.py", line 1055, in handleFile
>     print(self.__pattern.output_for(self.audio_file),
>   File "/usr/local/lib/python2.7/dist-packages/eyed3/plugins/display.py", line 45, in output_for
>     output += sub_pattern.output_for(audio_file)
>   File "/usr/local/lib/python2.7/dist-packages/eyed3/plugins/display.py", line 208, in output_for
>     output = self._get_output_for(audio_file)
>   File "/usr/local/lib/python2.7/dist-packages/eyed3/plugins/display.py", line 727, in _get_output_for
>     replacements))
>   File "/usr/local/lib/python2.7/dist-packages/eyed3/plugins/display.py", line 285, in _replace_placeholders
>     self._replace_placeholders(subtext, list(replacements)))
>   File "/usr/local/lib/python2.7/dist-packages/eyed3/plugins/display.py", line 285, in _replace_placeholders
>     self._replace_placeholders(subtext, list(replacements)))
>   File "/usr/local/lib/python2.7/dist-packages/eyed3/plugins/display.py", line 286, in _replace_placeholders
>     return (replacement[1] or "").join(subtexts)
> AttributeError: 'int' object has no attribute 'join'

Am I just running the command wrong or is this some sort of bug?

**Comment by nicfit** [comment]
Hi @KonomiKitten , thanks for reporting this. It is a bug, and I see a couple other problems too. I'll fix this soon.

**Comment by konomikitten** [comment]
@nicfit thanks, appreciate it a lot, any chance when you fix it you could also include an usage example, I still think I'm running it wrong but I'm unsure.

**Comment by nicfit** [comment]
With this fixes you should see something like this for a tag containing a single image.
```bash
$ eyeD3 --plugin=display --pattern '%images%'  test.mp3 
OTHER Image: [Type: image/jpeg] [Size: 26212 bytes]
```

**Comment by konomikitten** [comment]
@nicfit thank you for the how to and fix.
