### ISSUE TITLE
Is it possible to set PRIV fames?

### ISSUE THREAD

**Issue by njh** [nicfit/eyeD3#186]
Is it possible to set a PRIV frame using the eyeD3 command line?

The [HLS specification](https://tools.ietf.org/html/rfc8216#section-3.4) states that:

>    Each Packed Audio Segment MUST signal the timestamp of its first
>    sample with an ID3 Private frame (PRIV) tag [ID3] at the beginning of
>    the segment.  The ID3 PRIV owner identifier MUST be
>    "com.apple.streaming.transportStreamTimestamp".  The ID3 payload MUST
>    be a 33-bit MPEG-2 Program Elementary Stream timestamp expressed as a
>    big-endian eight-octet number, with the upper 31 bits set to zero.
>    Clients SHOULD NOT play Packed Audio Segments without this ID3 tag.

I have tried using `--text-frame` - but I guess it wants the frame to start with a 'T'?

```
~/Projects/wav-to-hls $ eyeD3 hls/1560E29B_000125.mp3 --text-frame PRIV:foo:bar
Setting PRIV text frame to 'foo:bar'
Invalid frame-id for text frame
```

**Comment by nicfit** [comment]
It is not part of the CLI tool, but pretty straight forward with the API.
```python
from eyed3.id3 import Tag

tag = Tag()
tag.privates.set(b"data", b"com.apple.streaming.transportStreamTimestamp")
tag.save("private.id3")
```

**Comment by njh** [comment]
Ok, thanks.
