### ISSUE TITLE
eyeD3 not setting exit code different than 0 when running --write-images on a file with no images

### ISSUE THREAD

**Issue by marcelpaulo** [nicfit/eyeD3#189]
I've just bumped into this while testing `--write-images` on a file without any images: if eyeD3 hits an error and outputs an error message to indicate it, it still sets the exit code to 0. So, we can't use eyeD3's exit code to check whether the operation was successful or not.

To reproduce it:

1. Create a dummy empty ID3 file: `touch foo.id3`
1. Try to show its tags with `eyeD3 foo.id3`, and immediately afterwards show the exit code:
    ```
    +paulo@monk:~/tmp$ eyeD3 foo.id3; echo $?
    /home/paulo/tmp/foo.id3                                                           [ 0.00 Bytes ]
    -------------------------------------------------------------------------------------------------
    No ID3 v1.x/v2.x tag found!
    0
    ```

I'm running latest eyeD3 from master (b8aa2c320dbcf22059fc9d132b832f5f8e28543a) on Xubuntu 17.10.

**Comment by nicfit** [comment]
Well, that is not really an error.  A special exit status for "no tags found" might be nice, and I think eyeD3 will exit non-zero when real errors occur, but will need to verify that.

**Comment by marcelpaulo** [comment]
> Well, that is not really an error

You've got a point there. It depends on what we consider a _successful operation_: if it is _eyeD3 managed to open the file and detect that there were no tags_, then you're right, it's not an error. But if it is _tags were shown_, then it is an error.

My original problem was trying to extract images with `--write-images`. I wanted to test whether an image was extracted. But we fall in the same argument: if the audio file has no images, it can be considered an error or not.

> I think eyeD3 will exit non-zero when real errors occur

The title of the issue is too generic, and seems to imply that. I got it wrong. I'll change it to reflect what I really tested. My bad, please forgive me.

**Comment by nicfit** [comment]
I'm not planning on implementing this myself @marcelpaulo . PRs welcome. Thanks for the many reports though!
