### ISSUE TITLE
EyeD3 command line, "nothing to do" with UTF-8 path (contain french characters )

### ISSUE THREAD

**Issue by lefuturiste** [nicfit/eyeD3#195]
With: Python 3.6.2, Windows 10 (1709), Git bash

I have file : `Musique d'été.mp3` on windows

When I try 

`$ eyeD3 "Musique d'été.mp3"`

I get the output :

 `Nothing to do` 

But I rename the file and replace `é` character with `e`, I get normal output with all tag informations.

How I can use file which contain UTF-8 Characters ?

Thanks.

**Comment by nicfit** [comment]
What version of eyeD3?

**Comment by LipsonX** [comment]
i found the problem in 0.8.5, cause image1.dll want a unicode with gbk coding path but python give a utf8 coding path. i found that you can roughly change 'filename.encode('utf-8')' to 'filename.encode('GBK')' of coerce_filename function in magic.py

**Comment by LipsonX** [comment]
i will try to fix first

**Comment by LipsonX** [comment]
sorry that. it is problem of magic.py. you can see in https://github.com/ahupp/python-magic/issues/165

**Comment by lefuturiste** [comment]
Ok thanks
