### ISSUE TITLE
FTBS: cannot create documentation with sphinx -- unexpected keyword argument 'keep_going'

### ISSUE THREAD

**Issue by Corin-EU** [nicfit/eyeD3#205]
On Linux Mint 18.3 (based on Ubuntu 16.04), for latest release eyeD3 0.8.5, using latest sphinx release 1.7.4, and with the necessary installation for some reason of sphinxcontrib-bitbucket, and the necessary addition of the the eyed3 source path to PYTHONPATH (otherwise eyed3.__init__ is not found), making man or html documentation fails.

      PYTHONPATH="${PYTHONPATH}:/usr/src/build/eyeD3-0.8.5/src" make html

     sphinx-build -b html -d _build/doctrees   . _build/html
      running Sphinx v1.7.4
     
     Configuration error:
     There is a programable error in your configuration file:

     Traceback (most recent call last):
       File "/usr/local/stow/Languages/Python/Sphinx-1.7.4/lib/python2.7/site-packages /Sphinx-1.7.4-py2.7.egg/sphinx/config.py", line 161, in __init__
         execfile_(filename, config)
       File "/usr/local/stow/Languages/Python/Sphinx-1.7.4/lib/python2.7/site-packages     /Sphinx-1.7.4-py2.7.egg/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
       File "/usr/lib/python2.7/dist-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
       File "<string>", line 1, in <module>
       File "conf.py", line 35, in <module>
    from eyed3.__about__ import (
       File "/usr/src/build/eyeD3-0.8.5/src/eyed3/__init__.py", line 32, in <module>
    from .utils.log import log                                          # noqa: E402
       File "/usr/src/build/eyeD3-0.8.5/src/eyed3/utils/__init__.py", line 53, in <module>
    _mime_types = MagicTypes()
       File "/usr/src/build/eyeD3-0.8.5/src/eyed3/utils/__init__.py", line 41, in __init__
    keep_going=False)
     TypeError: __init__() got an unexpected keyword argument 'keep_going'

     Makefile:53: recipe for target 'html' failed
     make: *** [html] Error 2

Is this a problem with the eyeD3 sphinx configuration or does it need to to be reported to the sphinx-doc project on Github for them to add 'keep_going' to the last of valid keywords?

**Comment by nicfit** [comment]
python-magic does not appear to be installed. This is the code in the traceback:
```python
class MagicTypes(magic.Magic):
    def __init__(self):
        magic.Magic.__init__(self, mime=True, mime_encoding=False,
                             keep_going=False)
```

What commands to reproduce?

**Comment by Corin-EU** [comment]
I just do not know if back in May 2018 whether or not python-magic was installed as a deb package or if was locally installed -- if the latter it may not have been getting found under /usr/local -- or if it was indeed installed at all and its lack therefore the cause of the  problem.

However, after an upgrade to latest Sphinx 1.8.3, installation of another requirement sphinx-issues (latest 1.2.0 released today), and attempted building of documents for latest eyeD3 0.8.8, the man + html + text documents do build successfully under python2.7

For html

sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.8.3
/usr/local/lib/python2.7/site-packages/requests-2.19.0-py2.7.egg/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
/usr/local/stow/Languages/Python2/sphinxcontrib-bitbucket-r.36be4abe62e5/lib/python2.7/site-packages/sphinxcontrib_bitbucket-1.0-py2.7.egg/sphinxcontrib/bitbucket.py:114: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  app.info('Initializing BitBucket plugin')
Initializing BitBucket plugin
making output directory...
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 25 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
writing output... [100%] usage                                                                                                                                                               
generating indices... genindex py-modindex
highlighting module code... [100%] eyed3.utils.prompt                                                                                                                                        
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

There is a warning during the manual page building to bring to your attention

/usr/src/build/eyeD3-0.8.8/src/eyed3/utils/__init__.py:docstring of eyed3.utils.os_walk:51: WARNING: Unexpected indentation.
/usr/src/build/eyeD3-0.8.8/src/eyed3/utils/__init__.py:docstring of eyed3.utils.os_walk:55: WARNING: Unexpected indentation.

As the building of documents does work successfully (with all the latest versions and with the necessary dependencies present and being found), this issue should be closed.
