### ISSUE TITLE
os.fwalk not available in windows

### ISSUE THREAD

**Issue by bradlis7** [nicfit/eyeD3#209]
It looks like #166 broke running eyed3 on windows. I changed it back from commit 5f7821487ee1cbeb1de8fb9e0c6d6b9d1d0329de, and it's working fine. Just needs a conditional if it's not a Unix OS.

**Comment by nicfit** [comment]
Thanks reporting. This also breaks Python2 support.

**Comment by nicfit** [comment]
Fixed in 57a7dfa25
