### ISSUE TITLE
accuracy in certain test cases is not precise

### ISSUE THREAD

**Issue by sezal98** [nicfit/eyeD3#210]
TinyTag result 
>>> tag = TinyTag.get('tests/silence-44-s-v1.mp3')
>>> print(tag.duration)
3.738712956446946

eyeD3 result
>>> audio = eyed3.load("tests/silence-44-s-v1.mp3").info.time_secs
>>> audio
3

there is a difference in precision.
/*
def test_mp3_length_estimation():
    ID3.set_estimation_precision(0.7)
    tag = TinyTag.get(os.path.join(testfolder, 'samples/silence-44-s-v1.mp3'))
    print(tag.duration)
    assert 3.5 < tag.duration < 4.0 
*/

**Comment by nicfit** [comment]
I'm not sure what you are saying. You want the value to be 3 instead of 3.7?

**Comment by sezal98** [comment]
no.. the value should be precise... it should be 3.7287...

**Comment by mlissner** [comment]
I think this issue regressed in the latest 0.9.7 release. We have an automated test in our repo that checks the output from `time_sec`. You can see it failing here, if you care:

https://github.com/freelawproject/doctor/actions/runs/3238182411/jobs/5306110959#step:5:16

The error says:

```
AssertionError: 51.64773161867487 != 51.64 : Bad duration
```

So in the past, I think eyed3 reported `51.64773161867487`, but now it returns `51.64`. 

I checked the latest release notes, but didn't see anything mentioned about this, so I suspect it's a mistake, but perhaps not. If it's a mistake, perhaps it should be reverted. If it's deliberate, perhaps a note in the release notes would help. 

I tried to find the commit that regressed this, but didn't find it, sorry.

I also took at look at the test that should have caught this, but it has some unfortunate rounding. I think [this line](https://github.com/nicfit/eyeD3/blob/master/tests/mp3/test_mp3.py#L81) should be changed from:

    assert round(audio_file.info.time_secs) == 262

To something like:

    assert audio_file.info.time_secs == pytest.approx(262.xyz)

(I'm not sure what the xyz is without getting tests up and running, but I'm guessing they just need to be plugged in.)

According to the [pytest docs](https://docs.pytest.org/en/latest/reference/reference.html#pytest.approx), that'll compare if the two numbers are within one one-millionth of each other, but it's easy to tweak to higher/lower tolerances.

Thanks for the great package, and again, if this is deliberate, I'll be perfectly happy just tweaking our test.

**Comment by WhitePeter** [comment]
@mlissner I found the commit (d2b14c67ae10cf77ea43055b92277d331ccdcc38) that regressed this. I don't know why but the author, seemingly, arbitrarily rounds `time_secs` to two decimal digits. I just stumbled on this while I was trying to fix the `fixup` plugin's handling of TLEN (PR pending), where a precision of at least down to a milliseconds, if not to sample length, seems advised.
