### ISSUE TITLE
eyeD3 always prints `Nothing to do`

### ISSUE THREAD

**Issue by refacto** [nicfit/eyeD3#226]
When I try doing anything with eyeD3, it prints `Nothing to do`.
For example, trying to change a ID3v2.4 tagged file to ID3v2.3:
```
~/Music/Nirvana/Nevermind > eyeD3 --to-v2.3 "05 Lithium.opus"
Nothing to do
```
Or, when trying to convert to 1.1:
```
~/Music/Nirvana/Nevermind > eyeD3 --to-v1.1 "05 Lithium.opus"
Nothing to do
```

**Comment by refacto** [comment]
Additional info. eyeD3 version:
```
~ > eyeD3 --version
eyeD3 0.7.8-final (C) Copyright 2002-2014 Travis Shirk
```
OS: Alpine Linux, edge up to date as of 2018-07-16

**Comment by nicfit** [comment]
What is an opus file? mp3? eyeD3 does not see it as such, therefore "Nothing to do"

**Comment by refacto** [comment]
An [Opus](https://opus-codec.org/) file is an [Ogg](https://en.wikipedia.org/wiki/Ogg) container file, with the audio encoded as Opus.

Will try if it works with mp3 files, but I recall that it did not.

**Comment by nicfit** [comment]
eyeD3 only works with mp3s.
