### ISSUE TITLE
utils.console module missing 

### ISSUE THREAD

**Issue by skorasaurus** [nicfit/eyeD3#23]
Hi, 

I'm using ubuntu 14.04; Python 2.7.6

To reproduce: 
1. create virtual env with ```mkdir .venv && virtualenv -p /usr/bin/python --no-site-packages .venv'```
2. initialize virtualenv ```'source .venv/bin/activate````
3. ```pip install eyed3```  returned ```Successfully installed eyed3-0.7.11```
4.  eyeD3 returns ```/home/myusername/myfilepath/eyed3_env/.venv/bin/python: No module named utils.console```

Seems like it's not finding the utils class in the install. Would it be a path problem on my end?

**Comment by nicfit** [comment]
I replicated your steps but the same results do not happen.

```
travis@iggy:/tmp
└> mkdir .venv && virtualenv -p /usr/bin/python2.7 --no-site-packages .venv
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /tmp/.venv/bin/python2.7
Also creating executable in /tmp/.venv/bin/python
Installing setuptools, pip, wheel...done.
travis@iggy:/tmp
└> source .venv/bin/activate
(.venv) travis@iggy:/tmp
└> pip install eyeD3
Collecting eyeD3
  Downloading eyeD3-0.7.11.tar.gz (234kB)
    100% |████████████████████████████████| 235kB 780kB/s 
Building wheels for collected packages: eyeD3
  Running setup.py bdist_wheel for eyeD3 ... done
  Stored in directory: /home/travis/.cache/pip/wheels/ee/ae/8f/c8a03a976906518a066b4f2663fdb17dc84cb9150603b4fce9
Successfully built eyeD3
Installing collected packages: eyeD3
Successfully installed eyeD3-0.7.11
(.venv) travis@iggy:/tmp
└> eyeD3
Nothing to do
(.venv) travis@iggy:/tmp
└> eyeD3 /home/travis/Music/Limiñanas\,\ The/2010\ -\ The\ Limiñanas/The\ Limiñanas\ -\ 01\ -\ The\ Darkside.mp3 
... The/2010 - The Limiñanas/The Limiñanas - 01 - The Darkside.mp3 [ 4.34 MB ]
-------------------------------------------------------------------------------
Time: 01:53	MPEG1, Layer III	[ 320 kb/s @ 44100 Hz - Joint stereo ]
-------------------------------------------------------------------------------
ID3 v2.4:
title: The Darkside
artist: The Limiñanas
album: The Limiñanas
album artist: The Limiñanas
release date: 2010
original release date: 2010
recording date: 2010
track: 1/12		genre: Psychedelic Rock (id 93)
Publisher/label: Trouble in Mind
UserTextFrame: [Description: replaygain_album_gain]
-11,52 dB
UserTextFrame: [Description: replaygain_track_gain]
-9,14 dB
UserTextFrame: [Description: replaygain_track_peak]
1,000000
UserTextFrame: [Description: DISCOGSID]
2553153
UserTextFrame: [Description: CATALOG]
TIM021
UserTextFrame: [Description: replaygain_album_peak]
1,000000
FRONT_COVER Image: [Size: 19448 bytes] [Type: image/jpeg]
Description: cover
-------------------------------------------------------------------------------

(.venv) travis@iggy:/tmp
└> eyeD3 --version
0.7.11
```

**Comment by skorasaurus** [comment]
Thanks for the prompt response. 

I upgraded my OS over the weekend (from ubuntu 14.04 to 16.04), a complete system refresh, so I reinstalled pip, virtualenv, etc. Alas, same result as before. 

I noticed that you used /usr/bin/python2.7 instead of /usr/bin/python but I repeated the steps twice on my new install one doing /usr/bin/python2.7 and once more with /usr/bin/python (deleted .venv before repeating my steps) and had the same issue. I'll take a look and try to figure out if it's a path problem or something else on my end.

**Comment by nicfit** [comment]
/usr/bin/python on my system is python3. I was explicit about 2.7 because that's what you are using.

**Comment by skorasaurus** [comment]
Not sure if you want to close this or not; but I installed it outside a virtualenv, doing  ```pip install --user eyeD3``` in my home directory and the command line usage of eyeD3 now works.  (which eyeD3 returns ```/home/myusername/.local/bin/eyeD3```(version 0.7.11) 

Thanks. If I have the time/skills and no one else does it, I'd add an option to the nfo option hat would include the artist for each track, so it could be used for multiple artists compilations.

**Comment by nicfit** [comment]
Glad it's working for you but the original problem is still strange. I run eyeD3 in a virtualenv 90% of the time so I'm still a bit curious about this.

**Comment by nicfit** [comment]
Closing for now, repopen if necessary  @skorasaurus
