### ISSUE TITLE
Don't overwrite logging.basicConfig

### ISSUE THREAD

**Issue by Lewistrick** [nicfit/eyeD3#243]
In .utils.log, `basicConfig()` from the `logging` module is called without parameters, setting the default logging stream to `stderr`. This is not recommended practice, and on top of that, highly annoying if one uses their own configuration.

**Comment by digglife** [comment]
Seriously?! This issue was fucking me around for about a hour!!! This change should reflect to PYPI ASAP. What a waste of time...

**Comment by digglife** [comment]
Thanks for the effort for the module though. It's very easy to use.
