### ISSUE TITLE
eyeD3 can't change recording-date

### ISSUE THREAD

**Issue by mooooonbaby** [nicfit/eyeD3#287]
Hi,

i have some mp3 files with the recording date 2016 and want to change it to 2018 with this command

[code]eyeD3 --recording-date 2018 input.mp3[/code]

the output is

[code]setting recording date: 2018[/code]

but when i display the file its still 2016.

**Comment by nicfit** [comment]
You'll have to paste some output to know what is displayed...

There are a few date fields; recording, release, original release, etc. `eyeD3 --recording-date` results in a `TDRC` frame. Many apps only show release date. But eyeD3 works as described above.
