### ISSUE TITLE
Something about file name recognition

### ISSUE THREAD

**Issue by duzhor** [nicfit/eyeD3#291]
The test found that when the file name is *.mp3 with the command "eyed3 song.mp3", it returns nothing to do, and with the script "audiofile = eyed3.load('song.mp3')" returns None.
When *.mp3 is replaced to *.id3, both methods can be read normally.

**Comment by nicfit** [comment]
Chances are that file mime-type detection is not find 'mp3' and so "Nothing to do". That msg could be better. I'd be careful during that rename trick. Without mp3 context eyeD3 is not trying to preserve audio data (.id3 contains none) when it rewrites. If there is not enough tag padding the audio can be corrupted.

What does `eyeD3 -ldebug` show for 'File mime-type'  ?

**Comment by duzhor** [comment]
E:\>eyed3 -ldebug 逆さまの蝶-SNoW.mp3
eyed3:DEBUG: command line args: Namespace(album=None, album_artist=None, artist=None, backup=False, bpm=None, comments=[], composer=None, config=None, convert_version=None, debug_pdb=False, debug_profile=False, disc_num=None, disc_total=None, encoding_date=None, excludes=None, force_update=False, fs_encoding='utf-8', genre=None, images=[], list_plugins=False, log_level=[['debug']], lyrics=[], max_padding=True, no_color=False, no_config=False, non_std_genres=False, objects=[], orig_release_date=None, paths=['逆さまの蝶-SNoW.mp3'], play_count=None, plugin=<classic.ClassicPlugin object at 0x0000022F77AA1668>, popularities=[], preserve_file_time=False, publisher=None, quiet=False, recording_date=None, release_date=None, release_year=None, remove_all=False, remove_all_comments=False, remove_all_images=False, remove_all_lyrics=False, remove_all_objects=False, remove_comment=[], remove_fids=[], remove_image=[], remove_lyrics=[], remove_object=[], remove_popularity=[], remove_v1=False, remove_v2=False, rename_pattern=None, simple_comment=None, tag_version=(3, None, None), tagging_date=None, text_encoding=None, text_frames=[], title=None, track=None, track_offset=None, track_total=None, unique_file_ids=[], url_frames=[], user_text_frames=[], user_url_frames=[], verbose=False, write_images_dir=None, write_objects_dir=None)
eyed3:DEBUG: plugin is: <classic.ClassicPlugin object at 0x0000022F77AA1668>
eyed3.core:DEBUG: Loading file: E:\逆さまの蝶-SNoW.mp3
eyed3.core:DEBUG: File mime-type: cannot open `E:\\351\200\206\343\201\225\343\201\276\343\201\256\350\235\266-SNoW.mp3' (No such file or directory)
Nothing to do

E:\>ren 逆さまの蝶-SNoW.mp3 逆さまの蝶-SNoW.id3

E:\>eyed3 逆さまの蝶-SNoW.id3
...E:\逆さまの蝶-SNoW.id3[ 11.53 MB ]
-------------------------
ID3 v2.3:
title: 逆さまの蝶
artist: SNoW
album: 逆さまの蝶
recording date: 2006
eyed3.id3:WARNING: Non standard genre name: J-Pop
track: 1                genre: J-Pop (id None)
disc: 1
Comment: [Description: ] [Lang: XXX]
163 key(Don't modify):L64FU3W4YxX3ZFTmbZ+8/VLqdKnPWBxrvyjUNDPEwYN1DqtKQJOFe1yM2VT5pdnGkggByLEdYX59W8hocEiYHPqDdIwN7uEK+PbR+C9tXxeSaa8fG7oYM2sc2O4znoQPhhniszvdGIZDa6TGlsMcS2HpZNAMKeowxkSjtuN0ALOG/kc1fNA5ihT5EavJeFoDHkFcR2WEaUsN0L7kMsIn/hexawbjK+jlhvyX5PV9chGK9e2shZIZMt+0HGzmkcJLnJQsp66kRsfLG20hDHlD+xsU9EBkwOO0/ANcB00YJ+efrS6DPcQvDhwdFuk3gO93fCNPdIx/n24BzEqD1Ww/6jgJGoI6H2PNW3BF3wNFQsjrmvoINCBtNphGyc0XA0S4H52zlX3DfRbko/UdXD1p/n36XOKvQY7y+dWdDKdxYr9SyDX/vh9KaprGu+cRjphrD8xVOEI4dt2YKwfsovJLlYStPf6Vhq1q5cRUvcIxydhhMokAMrfQTMQvDgHUCUt3ckkh81zLCSGfPM181D783g==
MEDIA Image: [Size: 1144692 bytes] [Type: image/jpeg]
Description:

-------------------------

E:\>

**Comment by duzhor** [comment]
Now I found that only when the file name is in English can it be read normally. 
it might be encode problem. But usually a lot of file names aren't just English.

**Comment by nicfit** [comment]
This is a duplicate of #218, problem is in pymagic.
