### ISSUE TITLE
File "magic" for contents fails when id3v2.4 tag frame length 512 - 521 inclusive

### ISSUE THREAD

**Issue by Corin-EU** [nicfit/eyeD3#303]
python version  3.5.2
mutagen version 1.41.1
eyeD3 version 0.8.8

When using the "file" command with a clean (non-tagged) MP3 file, one sees eg

X.mp3: MPEG ADTS, layer III, v1, 128 kbps, 44.1 kHz, JntStereo

and with an eyeD3 v2.4 tagged file, one usually (most cases) sees

X.mp3: Audio file with ID3 version 2.4.0, contains: MPEG ADTS, layer III, v1, 128 kbps, 44.1 kHz, JntStereo

The identification of the file contents as MPEG audio is essential for software which relies on "magic" to identify valid MP3 files, eg dircast which uses python-magic and creates XML lists of valid MP3 files.

However I have discovered that when eyeD3 creates an id3v2.4 tag whose length is 512 - 521 inclusive (using guessmp3enc to determine the value), "file" only reports

X.mp3: Audio file with ID3 version 2.4.0

and does not recognize the MPEG contents.

This arises when the total string length of the tags is between certain values - a range of 11 characters length.

If one of the tags (eg the URL tag, usually the longest) is not included in the initial tagging and is applied on its own on a subsequent application of eyeD3 then the problem does not occur.

What is bizarre about this is that the length of the id3tag header (now less than 512 remains unchanged after the URL tag is applied (and is verified as being present).

These observations would suggest that  perhaps there is a padding issue and if so, a bug in the calculation of the sizes needed.

I attach a Bourne shell script which illustrates the issue in two scenarios -one with multiple tags, and the simple case of just a title tag, which should work with any valid test MP3 file
named XX.mp3 in the current directory, except even when the file is named tagger.txt it refuses to upload. [Must be a new MicroSloth feature of Github and now Preview is broken as well.]

So instead it is on PasteBin at

https://pastebin.com/ehh1n8wC

**Comment by nicfit** [comment]
Can't reproduce.
