### ISSUE TITLE
lastfm plugin import failure

### ISSUE THREAD

**Issue by billsime** [nicfit/eyeD3#307]
I see this with eyeD3 version 0.8.8 under python 3.6.7

eyed3.plugins:WARNING: Plugin '('lastfm.py', '/usr/local/lib/python3.6/dist-packages/eyed3/plugins')' requires packages that are not installed: cannot import name 'COVER_EXTRA_LARGE'

Looks like it may be a fairly simple fix.

This is from lastfm.py:

from pylast import (COVER_EXTRA_LARGE, COVER_LARGE, COVER_MEDIUM, COVER_MEGA,
                    COVER_SMALL)

What is declared in pylast 3.0.0:

SIZE_SMALL = 0
SIZE_MEDIUM = 1
SIZE_LARGE = 2
SIZE_EXTRA_LARGE = 3
SIZE_MEGA = 4

**Comment by nicfit** [comment]
Thanks for the heads up.

Right now eyeD3 [supports](https://github.com/nicfit/eyeD3/blob/master/requirements.txt#L5) pylast 2.4.0. It looks like pylast 3.0.0 drops python2 support so eyeD3 0.8 cannot move to the latest version; eyeD3 and py2 support goes away only in the future.  The `devel` branch of eyeD3 is a suitable place to submit a PR against if you are interested, py2 support is dropped there.

**Comment by nicfit** [comment]
7c16d978ef1f9157ce5f73d8a0673a27b3142d8c

**Comment by apjanke** [comment]
I'm getting a similar error when trying to use the `lastfm` plugin. It looks like the `pylast` module isn't installed at all with a default installation of `eyeD3`. Is this expected? Do I need to pass extra arguments to `pip` to get all the plugin dependencies installed?

```
$ pip install eyeD3
Collecting eyeD3
  Using cached https://files.pythonhosted.org/packages/b9/43/bdd79ced1e7496d0a5f22b1c5c750e006d5f6931ba979235150ac819c052/eyeD3-0.8.8-py2.py3-none-any.whl
Requirement already satisfied: python-magic in /usr/local/lib/python3.7/site-packages (from eyeD3) (0.4.15)
Requirement already satisfied: six in /usr/local/Cellar/protobuf/3.6.1.3_1/libexec/lib/python3.7/site-packages (from eyeD3) (1.11.0)
Requirement already satisfied: pathlib in /usr/local/lib/python3.7/site-packages (from eyeD3) (1.0.1)
Installing collected packages: eyeD3
Successfully installed eyeD3-0.8.8
[~/tmp]
$ eyeD3 --add-image someimagefile.jpg:FRONT_COVER mymusicfile.m4a
eyed3.plugins:WARNING: Plugin '('lastfm.py', '/usr/local/lib/python3.7/site-packages/eyed3/plugins')' requires packages that are not installed: No module named 'pylast'
usage: eyeD3 [-h] [--version] [-l LEVEL[:LOGGER]] [--profile] [--pdb]
```

**Comment by billsime** [comment]
You've probably installed pylast 3.0 (as I did).  It was explained to me that 3.0 is not supported by eyeD3 0.8 and this is documented in the requirements.  The lastfm.py module attempts to import names from pylast (which were deprecated prior to 3.0) and which now no longer exist in the 3.0 version.  I installed the prior version with pip3 and this worked for me.

**Comment by nicfit** [comment]
@apjanke 

`pip install eyeD3[art-plugin]`

But only the next eyeD3 release will pin to pylast 2.x. Currently that pulls pylast 3.0.0, so you'll needed to uninstall and install ~= 2.0

**Comment by apjanke** [comment]
Thanks @nicfit! That's what I was looking for.

**Comment by nicfit** [comment]
@apjanke Check out eyeD3 0.8.9, this should not result in a compatible pylast.
