### ISSUE TITLE
audiofile.tag.title returns a string with a leading white space

### ISSUE THREAD

**Issue by Supportic** [nicfit/eyeD3#332]
I can't tell if it's just me but when I read the title of the track via audiofile.tag.title I'm getting a string back with a leading white space ` Title`.

I fixed it with `audiofile.tag.title.lstrip(' ')` but like I said I can't tell if it's only me experiencing it.

**Comment by nicfit** [comment]
There is likely leading whitespace the tag data then. eyeD3 does not auto-strip.
