### ISSUE TITLE
Where should bugs be reported?

### ISSUE THREAD

**Issue by daniel-barrows** [nicfit/eyeD3#333]
The bug tracker is listed as https://bitbucket.org/nicfit/eyed3/issues at the following places:
1. https://github.com/nicfit/eyed3#get-started
2. https://eyed3.readthedocs.io/en/latest/#get-started

However, I see [your BitBucket](https://bitbucket.org/nicfit/eyed3/) page says that you are switching / have switched to GitHub. Where would you like new bugs to be reported?

**Comment by nicfit** [comment]
Thanks for reporting this! Bugs should be reported here, at github. Bitbucket repo is no longer used.
