### ISSUE TITLE
Unable to "add" an artist tag

### ISSUE THREAD

**Issue by zaphodikus** [nicfit/eyeD3#334]
I have some files I created in audacity, years ago, some of them have no or missing tags.
    mp3 = eyed3.load(os.path.join(mypath, file))
    if not hasattr(mp3.tag, 'artist'):
        mp3.tag.artist = "unknown speaker"

throws exception
    mp3.tag.artist = "unknown speaker"
AttributeError: 'NoneType' object has no attribute 'artist'
Which I somewhat expected, but unclear and hope it's a documentation clarity, but how to add or set a tag is not working for file I loaded with no artist attribute. Had assumed that a setter or __attr__ wrapper was going to handle this.

**Comment by nicfit** [comment]
```
mp3.initTag()
mp3.tag.artist = "unknown speaker"
```
