### ISSUE TITLE
Rename Not Expanding Variables

### ISSUE THREAD

**Issue by kbpickens** [nicfit/eyeD3#336]
I'm hoping this is simply me missing something, but I am unable to rename files using the CLI tool.

When executing:
eyeD3 -l debug --rename "X$title" *
in a directory containing:
log  X.mp3
results in:
File '/mnt/nasv1/New Audio/W. Gibson/Neuromancer Disc 4/t/X.mp3' exists, will not overwrite

The debug output is:
`eyed3.plugins:WARNING: Plugin '('lastfm.py', '/home/kevin/.local/lib/python3.6/site-packages/eyed3/plugins')' requires packages that are not installed: No module named 'pylast'
eyed3:DEBUG: command line args: Namespace(album=None, album_artist=None, artist=None, backup=False, bpm=None, comments=[], composer=None, config=None, convert_version=None, debug_pdb=False, debug_profile=False, disc_num=None, disc_total=None, encoding_date=None, excludes=None, force_update=False, fs_encoding='utf-8', genre=None, images=[], list_plugins=False, log_level=[['debug']], lyrics=[], max_padding=True, no_color=False, no_config=False, non_std_genres=False, objects=[], orig_release_date=None, paths=['log', 'X.mp3'], play_count=None, plugin=<classic.ClassicPlugin object at 0xb6e95f0c>, popularities=[], preserve_file_time=False, publisher=None, quiet=False, recording_date=None, release_date=None, release_year=None, remove_all=False, remove_all_comments=False, remove_all_images=False, remove_all_lyrics=False, remove_all_objects=False, remove_comment=[], remove_fids=[], remove_image=[], remove_lyrics=[], remove_object=[], remove_popularity=[], remove_v1=False, remove_v2=False, rename_pattern='X', simple_comment=None, tag_version=(3, None, None), tagging_date=None, text_encoding=None, text_frames=[], title=None, track=None, track_offset=None, track_total=None, unique_file_ids=[], url_frames=[], user_text_frames=[], user_url_frames=[], verbose=False, write_images_dir=None, write_objects_dir=None)
eyed3:DEBUG: plugin is: <classic.ClassicPlugin object at 0xb6e95f0c>
eyed3.core:DEBUG: Loading file: /mnt/nasv1/New Audio/W. Gibson/Neuromancer Disc 4/t/log
eyed3.core:DEBUG: File mime-type: text/plain
eyed3.core:DEBUG: Loading file: /mnt/nasv1/New Audio/W. Gibson/Neuromancer Disc 4/t/X.mp3
eyed3.core:DEBUG: File mime-type: audio/mpeg
eyed3.id3.headers:DEBUG: Located ID3 v2 tag
eyed3.id3.headers:DEBUG: TagHeader [major]: 2 
eyed3.id3.headers:DEBUG: TagHeader [minor]: 3 
eyed3.id3.headers:DEBUG: TagHeader [rev]: 0 
eyed3.id3.headers:DEBUG: TagHeader [flags]: unsync(0) extended(0) experimental(0) footer(0)
eyed3.id3.headers:DEBUG: TagHeader [size string]: 0x00043d31
eyed3.id3.headers:DEBUG: TagHeader [size]: 73393 (0x11eb1)
eyed3.id3.frames:DEBUG: size_left: 73393
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #1
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 10 (0xA)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'TALB' (0x54414c42)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 19 (0x13)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 19 (0x13) bytes of data from byte pos 20 (0x14)
eyed3.id3.frames:DEBUG: FrameSet: 19 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Album/Movie/Show title) - (2, None, None) - <class 'eyed3.id3.frames.TextFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'TALB'' with class '<class 'eyed3.id3.frames.TextFrame'>'
eyed3.id3.frames:DEBUG: Unicode encoding: latin_1
eyed3.id3.frames:DEBUG: TextFrame text: Neuromancer Disc 4
eyed3.id3.frames:DEBUG: size_left: 73364
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #2
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 39 (0x27)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'TIT2' (0x54495432)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 5 (0x5)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 5 (0x5) bytes of data from byte pos 49 (0x31)
eyed3.id3.frames:DEBUG: FrameSet: 5 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Title/songname/content description) - (2, None, None) - <class 'eyed3.id3.frames.TextFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'TIT2'' with class '<class 'eyed3.id3.frames.TextFrame'>'
eyed3.id3.frames:DEBUG: Unicode encoding: latin_1
eyed3.id3.frames:DEBUG: TextFrame text: 4-12
eyed3.id3.frames:DEBUG: size_left: 73349
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #3
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 54 (0x36)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'MCDI' (0x4d434449)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 150 (0x96)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 150 (0x96) bytes of data from byte pos 64 (0x40)
eyed3.id3.frames:DEBUG: FrameSet: 150 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Music CD identifier) - (2, None, None) - <class 'eyed3.id3.frames.MusicCDIdFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'MCDI'' with class '<class 'eyed3.id3.frames.MusicCDIdFrame'>'
eyed3.id3.frames:DEBUG: size_left: 73189
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #4
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 214 (0xD6)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'TRCK' (0x5452434b)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 3 (0x3)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 3 (0x3) bytes of data from byte pos 224 (0xE0)
eyed3.id3.frames:DEBUG: FrameSet: 3 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Track number/Position in set) - (2, None, None) - <class 'eyed3.id3.frames.TextFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'TRCK'' with class '<class 'eyed3.id3.frames.TextFrame'>'
eyed3.id3.frames:DEBUG: Unicode encoding: latin_1
eyed3.id3.frames:DEBUG: TextFrame text: 12
eyed3.id3.frames:DEBUG: size_left: 73176
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #5
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 227 (0xE3)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'TCON' (0x54434f4e)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 10 (0xA)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 10 (0xA) bytes of data from byte pos 237 (0xED)
eyed3.id3.frames:DEBUG: FrameSet: 10 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Content type) - (2, None, None) - <class 'eyed3.id3.frames.TextFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'TCON'' with class '<class 'eyed3.id3.frames.TextFrame'>'
eyed3.id3.frames:DEBUG: Unicode encoding: latin_1
eyed3.id3.frames:DEBUG: TextFrame text: Audiobook
eyed3.id3.frames:DEBUG: size_left: 73156
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #6
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 247 (0xF7)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'PRIV' (0x50524956)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 14 (0xE)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 14 (0xE) bytes of data from byte pos 257 (0x101)
eyed3.id3.frames:DEBUG: FrameSet: 14 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Private frame) - (2, None, None) - <class 'eyed3.id3.frames.PrivateFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'PRIV'' with class '<class 'eyed3.id3.frames.PrivateFrame'>'
eyed3.id3.frames:DEBUG: size_left: 73132
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #7
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 271 (0x10F)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'PRIV' (0x50524956)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 17 (0x11)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 17 (0x11) bytes of data from byte pos 281 (0x119)
eyed3.id3.frames:DEBUG: FrameSet: 17 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Private frame) - (2, None, None) - <class 'eyed3.id3.frames.PrivateFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'PRIV'' with class '<class 'eyed3.id3.frames.PrivateFrame'>'
eyed3.id3.frames:DEBUG: size_left: 73105
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #8
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 298 (0x12A)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'PRIV' (0x50524956)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 41 (0x29)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 41 (0x29) bytes of data from byte pos 308 (0x134)
eyed3.id3.frames:DEBUG: FrameSet: 41 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Private frame) - (2, None, None) - <class 'eyed3.id3.frames.PrivateFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'PRIV'' with class '<class 'eyed3.id3.frames.PrivateFrame'>'
eyed3.id3.frames:DEBUG: size_left: 73054
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #9
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 349 (0x15D)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'PRIV' (0x50524956)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 39 (0x27)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 39 (0x27) bytes of data from byte pos 359 (0x167)
eyed3.id3.frames:DEBUG: FrameSet: 39 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Private frame) - (2, None, None) - <class 'eyed3.id3.frames.PrivateFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'PRIV'' with class '<class 'eyed3.id3.frames.PrivateFrame'>'
eyed3.id3.frames:DEBUG: size_left: 73005
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #10
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 398 (0x18E)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'PRIV' (0x50524956)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 40 (0x28)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 40 (0x28) bytes of data from byte pos 408 (0x198)
eyed3.id3.frames:DEBUG: FrameSet: 40 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Private frame) - (2, None, None) - <class 'eyed3.id3.frames.PrivateFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'PRIV'' with class '<class 'eyed3.id3.frames.PrivateFrame'>'
eyed3.id3.frames:DEBUG: size_left: 72955
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #11
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 448 (0x1C0)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'PRIV' (0x50524956)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 31 (0x1F)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 31 (0x1F) bytes of data from byte pos 458 (0x1CA)
eyed3.id3.frames:DEBUG: FrameSet: 31 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Private frame) - (2, None, None) - <class 'eyed3.id3.frames.PrivateFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'PRIV'' with class '<class 'eyed3.id3.frames.PrivateFrame'>'
eyed3.id3.frames:DEBUG: size_left: 72914
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #12
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 489 (0x1E9)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'PRIV' (0x50524956)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 34 (0x22)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 34 (0x22) bytes of data from byte pos 499 (0x1F3)
eyed3.id3.frames:DEBUG: FrameSet: 34 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Private frame) - (2, None, None) - <class 'eyed3.id3.frames.PrivateFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'PRIV'' with class '<class 'eyed3.id3.frames.PrivateFrame'>'
eyed3.id3.frames:DEBUG: size_left: 72870
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #13
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 533 (0x215)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'PRIV' (0x50524956)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 39 (0x27)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 39 (0x27) bytes of data from byte pos 543 (0x21F)
eyed3.id3.frames:DEBUG: FrameSet: 39 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Private frame) - (2, None, None) - <class 'eyed3.id3.frames.PrivateFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'PRIV'' with class '<class 'eyed3.id3.frames.PrivateFrame'>'
eyed3.id3.frames:DEBUG: size_left: 72821
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #14
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 582 (0x246)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'PRIV' (0x50524956)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 28 (0x1C)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 28 (0x1C) bytes of data from byte pos 592 (0x250)
eyed3.id3.frames:DEBUG: FrameSet: 28 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Private frame) - (2, None, None) - <class 'eyed3.id3.frames.PrivateFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'PRIV'' with class '<class 'eyed3.id3.frames.PrivateFrame'>'
eyed3.id3.frames:DEBUG: size_left: 72783
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #15
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 620 (0x26C)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'TPE2' (0x54504532)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 15 (0xF)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 15 (0xF) bytes of data from byte pos 630 (0x276)
eyed3.id3.frames:DEBUG: FrameSet: 15 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Band/orchestra/accompaniment) - (2, None, None) - <class 'eyed3.id3.frames.TextFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'TPE2'' with class '<class 'eyed3.id3.frames.TextFrame'>'
eyed3.id3.frames:DEBUG: Unicode encoding: latin_1
eyed3.id3.frames:DEBUG: TextFrame text: Robertson Dean
eyed3.id3.frames:DEBUG: size_left: 72758
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #16
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 645 (0x285)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'TPE1' (0x54504531)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 15 (0xF)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 15 (0xF) bytes of data from byte pos 655 (0x28F)
eyed3.id3.frames:DEBUG: FrameSet: 15 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Lead performer(s)/Soloist(s)) - (2, None, None) - <class 'eyed3.id3.frames.TextFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'TPE1'' with class '<class 'eyed3.id3.frames.TextFrame'>'
eyed3.id3.frames:DEBUG: Unicode encoding: latin_1
eyed3.id3.frames:DEBUG: TextFrame text: Robertson Dean
eyed3.id3.frames:DEBUG: size_left: 72733
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #17
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 670 (0x29E)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'TLEN' (0x544c454e)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 7 (0x7)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 7 (0x7) bytes of data from byte pos 680 (0x2A8)
eyed3.id3.frames:DEBUG: FrameSet: 7 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Length) - (2, None, None) - <class 'eyed3.id3.frames.TextFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'TLEN'' with class '<class 'eyed3.id3.frames.TextFrame'>'
eyed3.id3.frames:DEBUG: Unicode encoding: latin_1
eyed3.id3.frames:DEBUG: TextFrame text: 502933
eyed3.id3.frames:DEBUG: size_left: 72716
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #18
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 687 (0x2AF)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'TOLY' (0x544f4c59)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 15 (0xF)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 15 (0xF) bytes of data from byte pos 697 (0x2B9)
eyed3.id3.frames:DEBUG: FrameSet: 15 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Original lyricist(s)/text writer(s)) - (2, None, None) - <class 'eyed3.id3.frames.TextFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'TOLY'' with class '<class 'eyed3.id3.frames.TextFrame'>'
eyed3.id3.frames:DEBUG: Unicode encoding: latin_1
eyed3.id3.frames:DEBUG: TextFrame text: William Gibson
eyed3.id3.frames:DEBUG: size_left: 72691
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #19
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 712 (0x2C8)
eyed3.id3.headers:DEBUG: FrameHeader [id]: b'APIC' (0x41504943)
eyed3.id3.headers:DEBUG: FrameHeader [data size]: 71657 (0x117E9)
eyed3.id3.headers:DEBUG: FrameHeader [flags]: ta(0) fa(0) ro(0) co(0) en(0) gr(0) un(0) dl(0)
eyed3.id3.frames:DEBUG: FrameSet: Reading 71657 (0x117E9) bytes of data from byte pos 722 (0x2D2)
eyed3.id3.frames:DEBUG: FrameSet: 71657 bytes of data read
eyed3.id3.frames:DEBUG: createFrame (desc:Attached picture) - (2, None, None) - <class 'eyed3.id3.frames.ImageFrame'>
eyed3.id3.frames:DEBUG: createFrame 'b'APIC'' with class '<class 'eyed3.id3.frames.ImageFrame'>'
eyed3.id3.frames:DEBUG: APIC frame data size: 71657
eyed3.id3.frames:DEBUG: APIC mime type: b'image/jpeg'
eyed3.id3.frames:DEBUG: Initial APIC picture type: 3
eyed3.id3.frames:DEBUG: APIC picture type: 3
eyed3.id3.frames:DEBUG: description len: 0
eyed3.id3.frames:DEBUG: image len: 71643
eyed3.id3.frames:DEBUG: Unicode encoding: latin_1
eyed3.id3.frames:DEBUG: APIC description: 
eyed3.id3.frames:DEBUG: APIC image data: 71643 bytes
eyed3.id3.frames:DEBUG: size_left: 1024
eyed3.id3.frames:DEBUG: +++++++++++++++++++++++++++++++++++++++++++++++++
eyed3.id3.frames:DEBUG: FrameSet: Reading Frame #20
eyed3.id3.headers:DEBUG: FrameHeader [start byte]: 72379 (0x11ABB)
eyed3.id3.headers:DEBUG: FrameHeader: Null frame id found at byte 72383
eyed3.id3.frames:DEBUG: No frame found, implied padding of 1024 bytes
eyed3.id3.tag:DEBUG: Tag contains 1024 bytes of padding.
eyed3.mp3:DEBUG: mp3 header search starting @ 11ebb
eyed3.mp3.headers:DEBUG: MPEG audio version: 1.0
eyed3.mp3.headers:DEBUG: MPEG audio layer: III
eyed3.mp3.headers:DEBUG: MPEG sampling frequency: 44100
eyed3.mp3.headers:DEBUG: MPEG bit rate: 256
eyed3.mp3.headers:DEBUG: MPEG channel mode: Joint stereo
eyed3.mp3.headers:DEBUG: MPEG channel mode extension: 0
eyed3.mp3.headers:DEBUG: MPEG CRC error protection: False
eyed3.mp3.headers:DEBUG: MPEG original: 0
eyed3.mp3.headers:DEBUG: MPEG copyright: 0
eyed3.mp3.headers:DEBUG: MPEG private bit: 0
eyed3.mp3.headers:DEBUG: MPEG padding: 0
eyed3.mp3.headers:DEBUG: MPEG emphasis: None
eyed3.mp3.headers:DEBUG: MPEG frame length: 835
eyed3.mp3:DEBUG: mp3 header fffbd040 found at position: 0x11ebb
.../mnt/nasv1/New Audio/W. Gibson/Neuromancer Disc 4/t/X.mp3[ 15.40 MB ]
-------------------------
Time: 08:23	MPEG1, Layer III	[ 256 kb/s @ 44100 Hz - Joint stereo ]
-------------------------
ID3 v2.3:
title: 4-12
artist: Robertson Dean
album: Neuromancer Disc 4
album artist: Robertson Dean
track: 12		genre: Audiobook (id 183)
FRONT_COVER Image: [Size: 71643 bytes] [Type: image/jpeg]
Description: 

PRIV: [Data: 14 bytes]
Owner Id: PeakValue
PRIV: [Data: 17 bytes]
Owner Id: AverageLevel
PRIV: [Data: 41 bytes]
Owner Id: WM/MediaClassSecondaryID
PRIV: [Data: 39 bytes]
Owner Id: WM/MediaClassPrimaryID
PRIV: [Data: 40 bytes]
Owner Id: WM/Provider
PRIV: [Data: 31 bytes]
Owner Id: WM/WMContentID
PRIV: [Data: 34 bytes]
Owner Id: WM/WMCollectionID
PRIV: [Data: 39 bytes]
Owner Id: WM/WMCollectionGroupID
PRIV: [Data: 28 bytes]
Owner Id: WM/UniqueFileIdentifier

MCDI: [Data: 150 bytes]
File '/mnt/nasv1/New Audio/W. Gibson/Neuromancer Disc 4/t/X.mp3' exists, will not overwrite
-------------------------`

**Comment by nicfit** [comment]
Shell variable are expanded in double quotes, use single quotes.

**Comment by kbpickens** [comment]
That fixed it.
Cause: User Error
