### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by Lebostein** [nicfit/eyeD3#344]
What is this for a crap? I get this error on Windows and Mac OS.

**Comment by nicfit** [comment]
You need libmagic, which is needed my python-magic.

**Comment by Lebostein** [comment]
Is installed. But it don't work

**Comment by Lebostein** [comment]
Is there a specific version needed?

pip install libmagic
Requirement already satisfied: libmagic in /usr/local/lib/python2.7/site-packages (1.0)

>>> import eyed3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/eyed3/__init__.py", line 35, in <module>
    from .utils.log import log                                            # noqa
  File "/usr/local/lib/python2.7/site-packages/eyed3/utils/__init__.py", line 27, in <module>
    import magic
  File "/usr/local/lib/python2.7/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by nicfit** [comment]
There is a system library needed. I only have/test on linux, but I'm pretty
sure brew is used to install it on Mac but I have no idea what to do on
Windows.

Answer is likely here:
https://github.com/nicfit/eyeD3/issues?utf8=%E2%9C%93&q=is%3Aissue+libmagic

-travis

**Comment by Lebostein** [comment]
OK. With "brew install libmagic" it works.
Can you please catch this error/problem and write a warning/hint in your code?

**Comment by rmwphd** [comment]
Hear hear! If the pip installed libmagic isn't sufficient, it would be nice to have a warning, at least, if not a built-in solution.

**Comment by Christilut** [comment]
I had to install `python-magic==0.4.14` and `python-magic-bin==0.4.14`

**Comment by nicfit** [comment]
Hi all, I just committed the removal of python-magic. Life might be easier for eyeD3 0.9 in this regard. It'll definitely be **faster**!

26602194ef7c3ff7b2296ae8a65698d70d8c7157

**Comment by wiraszka** [comment]
As Christilut pointed out, `pip install python-magic-bin==0.4.14` fixes this issue on windows

**Comment by nicfit** [comment]
As of eyeD3 0.9 libmagic is no longer required.
