### ISSUE TITLE
Why are you removing versions?

### ISSUE THREAD

**Issue by XiaonuoGantan** [nicfit/eyeD3#380]
I noticed that you have been removing versions on pypi.org since 2019/12/29. On 12/29, you removed version 0.8.7. On 01/02, you removed version 0.8.8. Can you let me know why you are removing the existing versions?

**Comment by nicfit** [comment]
Sorry if I removed version you've pinned, but each of the version you refer to are well 1 year old and there are minor version releases that fix bugs.  I don't want to continue to support those older versions. Now that eyeD3 0.9 is out I'd like to get to a point where only the latest 0.8 is available so I'm slowing removing older versions.

**Comment by XiaonuoGantan** [comment]
Got it. Thank you for the explanation.
