### ISSUE TITLE
Typo in eyed3/utils/__init__.py causes Syntax Error during import

### ISSUE THREAD

**Issue by Acer54** [nicfit/eyeD3#381]
Hello,
with commit [bbfd1bd](https://github.com/nicfit/eyeD3/commit/bbfd1bd874a96dc130aa78a0dfb45bbd4914410e) a typo in line [361](https://github.com/nicfit/eyeD3/blob/52d61e95b337d2c8d5f3661f4137b81dafb2ab31/eyed3/utils/__init__.py#L361) causes a Syntax Error when called:

```python
Traceback (most recent call last):
    import eyed3
  File "/usr/local/lib/python2.7/dist-packages/eyed3/__init__.py", line 30, in 
    from .utils.log import log                                          # noqa: E402
  File "/usr/local/lib/python2.7/dist-packages/eyed3/utils/__init__.py", line 361
    msg = f"invalid level choice: {level} (choose from {parser.log_levels})"
           ^
SyntaxError: invalid syntax
```
eyed3 was installed and upgraded via pip in a fresh Debian Buster.

EDIT: I have simulated this with an Ubuntu 18.04 and attached a log.
[errorlog.txt](https://github.com/nicfit/eyeD3/files/4027482/errorlog.txt)

Regards,
Matthias

**Comment by nicfit** [comment]
Hi @Acer54 , thanks for the report. This is not a syntax error, rather it is python f-strings. What version of Python are you using? eyeD3 0.9 only support >= 3.6. Sick to the 0.8 version if using 2.7, <=3.5

**Comment by Acer54** [comment]
Hi @nicfit, 
thanks for your feedback! 
You are right, I am using Python 2.7 for my own project which is still based on 2.7. To be honest, "f-strings" where new to me ;-) ... In the meantime I read about.
Anyway, it was not obvious to me, that this lib is not compatible with 2.7 any more. Maybe you should make that more clear?
[Here](http://eyed3.nicfit.net/) is "Python 2.7, >=3.3 Required".
[Requirements.txt](https://github.com/nicfit/eyeD3/blob/master/requirements.txt) says "python_version < "3.7"
[PyPi.org](https://pypi.org/project/eyeD3/) says "Python >= 3.6 is required."

I am not sure how pip handles python requirements for these packages, but from my point of view it should not be possible to install a package in 2.7 which is not compatible with this version (?)
Maybe it is something with the "[python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires)" metadata?  But like I said, I am no expert in this...

I will correct my installer accordingly, in order to choose a version < 0.9 (0.8.10 was working for me so far...) 
By the way, thanks for your support and efforts which you invest in your project here!

Regards,
Matthias

**Comment by nicfit** [comment]
`

> You are right, I am using Python 2.7 for my own project which is still based on 2.7. To be honest, "f-strings" where new to me ;-) ... In the meantime I read about.

As of 1/1/2020, python 2.7 is end-of-life, you must consider NOT using it. :)

> [Here](http://eyed3.nicfit.net/) is "Python 2.7, >=3.3 Required".

Out of date, thanks for the reminder.

> [Requirements.txt](https://github.com/nicfit/eyeD3/blob/master/requirements.txt) says "python_version < "3.7"

The line in requirements.txt is for the dataclasses dependency, which is required for any version < 3.7. In this case it only applies to python3.6

> [PyPi.org](https://pypi.org/project/eyeD3/) says "Python >= 3.6 is required."

This is the truth.
 
> I am not sure how pip handles python requirements for these packages, but from my point of view it should not be possible to install a package in 2.7 which is not compatible with this version (?)
> Maybe it is something with the "[python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires)" metadata? But like I said, I am no expert in this...

Sadly, it does not.

> 
> I will correct my installer accordingly, in order to choose a version < 0.9 (0.8.10 was working for me so far...)

Yea, use `eyeD3<0.9` as a dep until you can upgrade to python3; but do so ASAP because py2 is a dead end street. Thanks for using eyeD3
