### ISSUE TITLE
certain genres still write as ids with non_std_genres

### ISSUE THREAD

**Issue by j4ix** [nicfit/eyeD3#382]
so far i've found that dubstep, electro, chillout, hardcore, and drum & bass are rendering as id's when parsed through the non_std_genre method

**Comment by j4ix** [comment]
this problem doesn't exist in mutagen, swapping my code

**Comment by j4ix** [comment]
alright i'm gonna try this once more, because eyed3 has been working fine so far and it would be a pain in the ass to swap everything out.

if a track labels itself as a specific genre and i run this code:
```
import eyed3

meta = eyed3.load('C:/Users/j4ix/Documents/temp/sometrack.mp3')
genre = meta.tag.genre
print(genre)
print(type(genre))
meta.tag.non_std_genre = genre
```
some tracks will have their genres written to file as an id.

**Comment by nicfit** [comment]
@j4ix I try and take a look at this. But some genres **are** numbers. In fact ID3 v1.x they must be numbers that map to https://en.wikipedia.org/wiki/List_of_ID3v1_Genres.   eyeD3 will do so e of this mapping IIRC, but does not rewrite

**Comment by j4ix** [comment]
@nicfit thats the problem, i’ve even went as far instantiating the `eyed3.id3.Genre` object on my own with an `id` of `None` and the `name` being a genre in string format pulled directly from soundcloud json. then i passed it through non_std_genre or genre, hell i tried manually setting id3_std through a private function

it doesn’t seem to matter what it’s given it’ll parse it no matter what, even if i thought all of this stuff was supposed to keep it from doing so, i’ve debated doing things like removing or changing the whole table of genres to fix this but idk where the problem lies

i would like it to work but in the meantime i’m batch selecting hundreds of songs in itunes created with an id of `189` and manually changing it to `Dubstep`

**Comment by j4ix** [comment]
i’m working with tags in id3 v2.3 and i literally want eyed3 to put verbatim what i give it as a genre into the tag. it always seems to parse it for an id first no matter what and if it matches the list it’s goin in the tag as an id.

**Comment by nicfit** [comment]
eyeD3 really tries hard to write in the format defined in ID3 v2.3 [TCON spec](http://id3.org/id3v2.3.0#Text_information_frames_-_details). This is prolly overly pedantic, and ID3 v2.4 drops the format. I'll likely make it easier to set the "raw" genre, but in the meantime this should get what you want...
```python
meta.tag.setTextFrame("TCON", "Dubstep")
```
You'll still see/get a `Dubstep (id 189)` genre object but the **data** is simply `Dubstep`. Also, even  if setGenre("raw") happens the Genre object will always map to an ID value if possible.

**Comment by j4ix** [comment]
@nicfit greatly appreciate it! but yes pleeeease do consider adding a built-in way to do that, because out of wmp itunes and groove so far they all just show 189 instead of an actual genre. i’ll implement your fix into my code.

**Comment by j4ix** [comment]
once again greatly appreciate this change. workin on new code today, implementing the proper fix into it now.
