### ISSUE TITLE
No output from CLI. Blocks all Python interpreter output after import.

### ISSUE THREAD

**Issue by aamikus** [nicfit/eyeD3#388]
I have a really weird issue. I installed eyeD3 with `pip install eyeD3`. It successfully installed and appears in `pip freeze`.

Now, whenever I try to run a CLI command, even `eyed3 -- help`, my console outputs nothing. Same thing if I try to output file info with `eyed3 file.mp3`

If I open the python interpreter in the console and import eyed3, any other code I write after this import is not run in the interpreter. Even for a print statement, the output is empty and the interpreter just skips to the next line.

This happened both with a virtualenv and without.

Setup:
- macOs
- Python 3.7.4
- pip 20.0.2

**Comment by nicfit** [comment]
This is a problem with the latest release and stab and a fix for Windows.. Can you try:
"pip install eyeD3==0.9" and try again?

**Comment by nicfit** [comment]
@aamikus Thanks for reporting this. eyeD3 0.9.2 should now work for you.

PYTHOPNIOENCODING was to fix issues: #383  #368 but has been reverted.
