### ISSUE TITLE
eyeD3 version 0.9.x not working on slackware

### ISSUE THREAD

**Issue by oldpink** [nicfit/eyeD3#390]
I've been a very happy user of eyeD3 for several years now, so I tried compiling version 0.9.2 of it, only for it to fail with the error below:

Traceback (most recent call last):
  File "/usr/bin/eyeD3", line 11, in <module>
    load_entry_point('eyeD3==0.9.2', 'console_scripts', 'eyeD3')()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/eyed3/__init__.py", line 31, in <module>
    from .utils.log import log                                          # noqa: E402
  File "/usr/lib64/python2.7/site-packages/eyed3/utils/__init__.py", line 361
    msg = f"invalid level choice: {level} (choose from {parser.log_levels})"
                                                                           ^
SyntaxError: invalid syntax

This isn't a total loss, as I just switched back to version 0.8.12 for the time being, but it would be nice to be able to run the newer versions to stay current, but there is probably some dependency that I have no idea is missing that makes that impossible.
What did I get wrong?

**Comment by nicfit** [comment]
@oldpink 0.9.x requires >= python3.6.  I see you are using 2.7

**Comment by oldpink** [comment]
basename /var/log/packages/python3-3.8.1-x86_64-1
python3-3.8.1-x86_64-1

That's what has me so puzzled.
I even tried switching from Python2 to Python3 in my build script (SlackBuild), but even that didn't help.

**Comment by nicfit** [comment]
How did you install eyeD3? I see it is /usr/bin/eyeD3 inm your output, and /usr/lib64/python2.7/ python?

**Comment by oldpink** [comment]
**I used a SlackBuild script (Slackware bash build script) to automate the build process.
I can show the locations for all of the installed files
Here is that build script:**

#!/bin/sh
# Slackware build script for eyeD3
# Copyright 2007  Andrew Lindberg <alindberg@gmail.com>
# Copyright 2015 Andrew Strong, Blue Mountains Australia.
# Copyright 2016-2019 Larry Hajali <larryhaja[at]gmail[dot]com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Modified by the SlackBuilds.org project
# No additional license terms added
# Modified by new maintainer: Andrew Strong

PRGNAM=eyeD3
VERSION=${VERSION:-0.8.10}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Install for python3.
python3 setup.py install --root=$PKG

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a *.rst $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}

**Here are the install locations using this script:**

/usr/bin/eyeD3
/usr/doc/eyeD3-0.9.2/AUTHORS.rst
/usr/doc/eyeD3-0.9.2/CONTRIBUTING.rst
/usr/doc/eyeD3-0.9.2/HISTORY.rst
/usr/doc/eyeD3-0.9.2/README.rst
/usr/doc/eyeD3-0.9.2/eyeD3.SlackBuild
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/PKG-INFO
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/SOURCES.txt
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/dependency_links.txt
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/entry_points.txt
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/not-zip-safe
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/requires.txt
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/top_level.txt
/usr/lib64/python3.8/site-packages/eyed3/__about__.py
/usr/lib64/python3.8/site-packages/eyed3/__init__.py
/usr/lib64/python3.8/site-packages/eyed3/__pycache__/__about__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/__pycache__/__init__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/__pycache__/core.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/__pycache__/main.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/__pycache__/mimetype.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/core.py
/usr/lib64/python3.8/site-packages/eyed3/id3/__init__.py
/usr/lib64/python3.8/site-packages/eyed3/id3/__pycache__/__init__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/id3/__pycache__/apple.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/id3/__pycache__/frames.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/id3/__pycache__/headers.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/id3/__pycache__/tag.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/id3/apple.py
/usr/lib64/python3.8/site-packages/eyed3/id3/frames.py
/usr/lib64/python3.8/site-packages/eyed3/id3/headers.py
/usr/lib64/python3.8/site-packages/eyed3/id3/tag.py
/usr/lib64/python3.8/site-packages/eyed3/main.py
/usr/lib64/python3.8/site-packages/eyed3/mimetype.py
/usr/lib64/python3.8/site-packages/eyed3/mp3/__init__.py
/usr/lib64/python3.8/site-packages/eyed3/mp3/__pycache__/__init__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/mp3/__pycache__/headers.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/mp3/headers.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/__init__.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/__init__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/_display_parser.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/art.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/classic.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/display.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/extract.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/fixup.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/genres.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/itunes.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/jsontag.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/lameinfo.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/lastfm.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/mimetype.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/nfo.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/pymod.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/stats.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/xep_118.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/yamltag.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/_display_parser.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/art.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/classic.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/display.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/extract.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/fixup.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/genres.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/itunes.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/jsontag.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/lameinfo.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/lastfm.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/mimetype.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/nfo.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/pymod.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/stats.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/xep_118.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/yamltag.py
/usr/lib64/python3.8/site-packages/eyed3/utils/__init__.py
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/__init__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/art.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/binfuncs.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/console.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/log.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/prompt.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/art.py
/usr/lib64/python3.8/site-packages/eyed3/utils/binfuncs.py
/usr/lib64/python3.8/site-packages/eyed3/utils/console.py
/usr/lib64/python3.8/site-packages/eyed3/utils/log.py
/usr/lib64/python3.8/site-packages/eyed3/utils/prompt.py

**Comment by oldpink** [comment]
I used a SlackBuild script (Slackware bash build script) to automate the build process.
I can show the locations for all of the installed files
Here is that build script:

#!/bin/sh
# Slackware build script for eyeD3
# Copyright 2007  Andrew Lindberg <alindberg@gmail.com>
# Copyright 2015 Andrew Strong, Blue Mountains Australia.
# Copyright 2016-2019 Larry Hajali <larryhaja[at]gmail[dot]com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Modified by the SlackBuilds.org project
# No additional license terms added
# Modified by new maintainer: Andrew Strong

PRGNAM=eyeD3
VERSION=${VERSION:-0.8.10}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Install for python3.
python3 setup.py install --root=$PKG

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a *.rst $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}

Here are the install locations using this script:

/usr/bin/eyeD3
/usr/doc/eyeD3-0.9.2/AUTHORS.rst
/usr/doc/eyeD3-0.9.2/CONTRIBUTING.rst
/usr/doc/eyeD3-0.9.2/HISTORY.rst
/usr/doc/eyeD3-0.9.2/README.rst
/usr/doc/eyeD3-0.9.2/eyeD3.SlackBuild
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/PKG-INFO
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/SOURCES.txt
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/dependency_links.txt
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/entry_points.txt
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/not-zip-safe
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/requires.txt
/usr/lib64/python3.8/site-packages/eyeD3-0.9.2-py3.8.egg-info/top_level.txt
/usr/lib64/python3.8/site-packages/eyed3/__about__.py
/usr/lib64/python3.8/site-packages/eyed3/__init__.py
/usr/lib64/python3.8/site-packages/eyed3/__pycache__/__about__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/__pycache__/__init__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/__pycache__/core.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/__pycache__/main.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/__pycache__/mimetype.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/core.py
/usr/lib64/python3.8/site-packages/eyed3/id3/__init__.py
/usr/lib64/python3.8/site-packages/eyed3/id3/__pycache__/__init__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/id3/__pycache__/apple.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/id3/__pycache__/frames.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/id3/__pycache__/headers.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/id3/__pycache__/tag.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/id3/apple.py
/usr/lib64/python3.8/site-packages/eyed3/id3/frames.py
/usr/lib64/python3.8/site-packages/eyed3/id3/headers.py
/usr/lib64/python3.8/site-packages/eyed3/id3/tag.py
/usr/lib64/python3.8/site-packages/eyed3/main.py
/usr/lib64/python3.8/site-packages/eyed3/mimetype.py
/usr/lib64/python3.8/site-packages/eyed3/mp3/__init__.py
/usr/lib64/python3.8/site-packages/eyed3/mp3/__pycache__/__init__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/mp3/__pycache__/headers.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/mp3/headers.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/__init__.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/__init__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/_display_parser.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/art.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/classic.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/display.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/extract.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/fixup.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/genres.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/itunes.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/jsontag.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/lameinfo.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/lastfm.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/mimetype.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/nfo.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/pymod.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/stats.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/xep_118.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/__pycache__/yamltag.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/plugins/_display_parser.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/art.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/classic.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/display.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/extract.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/fixup.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/genres.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/itunes.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/jsontag.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/lameinfo.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/lastfm.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/mimetype.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/nfo.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/pymod.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/stats.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/xep_118.py
/usr/lib64/python3.8/site-packages/eyed3/plugins/yamltag.py
/usr/lib64/python3.8/site-packages/eyed3/utils/__init__.py
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/__init__.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/art.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/binfuncs.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/console.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/log.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/__pycache__/prompt.cpython-38.pyc
/usr/lib64/python3.8/site-packages/eyed3/utils/art.py
/usr/lib64/python3.8/site-packages/eyed3/utils/binfuncs.py
/usr/lib64/python3.8/site-packages/eyed3/utils/console.py
/usr/lib64/python3.8/site-packages/eyed3/utils/log.py
/usr/lib64/python3.8/site-packages/eyed3/utils/prompt.py

**Comment by nicfit** [comment]
Well, that file list looks legit to me. I'm guessing there is an issue with the slackware build since you're OP stacktrace shows that python2.7 being used.

**Comment by oldpink** [comment]
I tried resolving this by also recompiling and reinstalling from source the four dependencies for eyeD3, this time building the dependencies to use python3 instead of python2, but it still fails: pathlib, pylast, python-magic, six

I **was** able to get rid of the error messages about a dependency built for python2 when I built eyeD3 0.8.12 with python3 with those dependencies also built that way, though.

**Comment by oldpink** [comment]
Here is the output when attempting to run version 0.9.2 after recompiling the dependencies and eyeD3 with python3:

Traceback (most recent call last):
  File "/usr/bin/eyeD3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'deprecation' distribution was not found and is required by eyeD3

**Comment by nicfit** [comment]
Install `deprecation`. See requirements.txt for the full list.

**Comment by oldpink** [comment]
Whoah!
I installed all of the source files listed in requirements.txt, including deprecation, and it suddenly works perfectly.
Thank you so much.
Problem solved

Output of "eyeD3 --version"
0.9.2

All is well with the world.
