### ISSUE TITLE
Loading file bug!

### ISSUE THREAD

**Issue by jzr-supove** [nicfit/eyeD3#391]
I'm trying to open a file called `Тимати - Я еду на джипе.mp3`, but it is returning `None`.
When I renaming this file to `Timati - Ya edu na djipe.mp3`, it is working.

I think there is a bug with file name encoding!

To see what is happening under the hood.
I put `print("Mtype:", mtype)` inside `eyed3.load()` function after the line `mtype = guessMimetype(path)`

I got the output: 

> Mtype: cannot open \320\242\320\270\320\274\320\260\321\202\320\270 - \320\257 \320\265\320\264\321\203 \320\275\320\260 \320\264\320\266\320\270\320\277\320\265.mp3' (No such file or directory)

Please fix this error as soon as possible!

**Comment by jzr-supove** [comment]
Somehow I solved this problem!

Inside `eyed3.load` function, after the line 
```
mtype = guessMimetype(path)
```
I have added these lines of code :
```
if mtype.startswith('cannot open'):
    mtype = 'audio/mpeg'
```

**Taddaaam, problem solved)**

**Comment by nicfit** [comment]
What's your platform and eyeD3 version?

**Comment by jzr-supove** [comment]
@nicfit 
Platform: Windows 10 Pro (x64)
eyeD3 version: 0.8.10

**Comment by nicfit** [comment]
@GooDeeJaY , libmagic is not used by the latest 0.9.x versions of eyeD3, so should  not have this problem.

**Comment by nicfit** [comment]
Dupicate of #218
