### ISSUE TITLE
Unset/remove DATE

### ISSUE THREAD

**Issue by jneidel** [nicfit/eyeD3#392]
I'd like to remove the dates of my files via the CLI.

What can I pass to `--release-date`,  `--orig-release-date` and `--recording-date` to unset them?

**Comment by nicfit** [comment]
Empty string.

**Comment by jneidel** [comment]
> Empty string.

Already tried that, does not work:

```sh
$ eyeD3 --release-date "" 02.\ Denzel\ Curry\ -\ Ricky.mp3 

/home/jneidel/tmp/02. Denzel Curry - Ricky.mp3                     [ 6.04 MB ]
-------------------------------------------------------------------------------
Setting release date: 
Invalid date string: 
```

**Comment by jneidel** [comment]
And `null`, `false` or anything like that don't work either, because it does not match the [Date](https://eyed3.readthedocs.io/en/latest/eyed3.html?highlight=date#eyed3.core.Date) type formats.

**Comment by nicfit** [comment]
what version  of eyeD3? I did it with latest 0.9.2.

**Comment by jneidel** [comment]
0.8

From the [arch package](https://www.archlinux.org/packages/community/any/python-eyed3/). Which was flagged outdated 2+ years ago...

**Comment by nicfit** [comment]
0.8 is quite out and that bug has been fixed in later versions. I reached out to arch maintainers a while back about this (I use arch myself) but should follow up. In  them meantime, update your eyeD3 and you'll get this feature.

**Comment by jneidel** [comment]
Will do, thanks!
