### ISSUE TITLE
Crash when updating email frame due to bad encode() call

### ISSUE THREAD

**Issue by sharkusk** [nicfit/eyeD3#397]
Line 956 in frames.py:

    self._email = email.encode(ascii_encode)

This fails because ascii_encode is a function and the encode() function expects a string.  I believe the following should work:

    self._email = email.encode('ascii')

**Comment by nicfit** [comment]
Thanks for reporting this @sharkusk !

**Comment by nicfit** [comment]
Fixed by 11abd2c0fbc80d8525f5f0d92eb3d619782cfea7
