### ISSUE TITLE
Using Eyed3 with PythonKit

### ISSUE THREAD

**Issue by NCrusher74** [nicfit/eyeD3#401]
I've only been learning Swift for the last six months or so, and I'm not familiar with python at all, but the syntax looks similar enough I think I can learn.

In Swift, I've been trying to make a framework for handling audiobook-specific metadata, but I'm having trouble finding an ID3 editor that has all the frames I need, especially CHAP, and can be used in Swift. 

Thanks to PythonKit, however, it looks like EyeD3 could be the answer to my problem, if only I can get it to work to start familiarizing myself with it.

```swift
    func testImport() {
        let sys = Python.import("sys")
        sys.path.append("<path to EyeD3 directory>")
        let eyeD3 = Python.import("<something (where "something" is a .py file)>"
    }
```

This is about as far as I've gotten. Has anyone used this and if so, how did they make it work?

**Comment by nicfit** [comment]
Sounds cool @NCrusher74 .  Good luck and send updates.

**Comment by NCrusher74** [comment]
Well, I'd hoped that someone had had some experience using it because I can't figure it out. Ah well.
