### ISSUE TITLE
It does not work for Python3 3.5.2

### ISSUE THREAD

**Issue by ghost** [nicfit/eyeD3#405]
It returns 

`Traceback (most recent call last):
  File "mixer_s3.py", line 29, in <module>
    import eyed3
  File "/home/ubuntu/.local/lib/python3.5/site-packages/eyed3/__init__.py", line 31, in <module>
    from .utils.log import log                                          # noqa: E402
  File "/home/ubuntu/.local/lib/python3.5/site-packages/eyed3/utils/__init__.py", line 361
    msg = f"invalid level choice: {level} (choose from {parser.log_levels})"
                                                                           ^
SyntaxError: invalid syntax`

So not as the documentation suggests:

eyeD3 0.9.4 has been tested with Python 2.7, >=3.3

Thanks

**Comment by nicfit** [comment]
Thanks for pointing this out @bacloud14 . It's an error in the documentation. 0.8 meets those requirements, but 0.9 is py3 only.

**Comment by ghost** [comment]
So can I down-grade to 0.8 to run on Python 3.5 ? 
Thanks

**Comment by nicfit** [comment]
> So can I down-grade to 0.8 to run on Python 3.5 ?

Correct, 0.8.12 is the latest in that series.
