### ISSUE TITLE
lameinfo CRC question

### ISSUE THREAD

**Issue by atomGit** [nicfit/eyeD3#410]
the lameinfo plugin prints 2 CRCs -- one for the tag, one for the audio -- but does it/can it calculate a checksum for the audio stream and compare it to the CRC in the tag?

in other words, if the audio is altered then a checksum derived from the audio will not/should not match that in the LAME tag (mp3gain aside) -- will lameinfo let us know if the CRCs don't match?

i wold have the same Q for the CRC of the tag itself - how does the CRC tell us if the tag was altered?

**Comment by nicfit** [comment]
@atomGit [Here](https://github.com/nicfit/eyeD3/commit/859a2f083c44e2fd86cf1e73e4771886b2a3f3f1#diff-432df6dd3b2e366c093cc277dc20000dR576) is the only place CRC checks occur. Without looking at specs I can't remember exactly what is being computed/checked... but I did add a new debug log when it passes.. I have lots of files that pass and fail in my collection.

I believe file alteration would affect this check as well.

**Comment by atomGit** [comment]
i picked up development on my shell script again and i'm still stumped by this original issue - allow me to refresh myself

so if i encode a flac to mp3 for example, then run eyeD3 on it, i'm seeing 2 different CRC values...

```
Music CRC-16        : A9C2
LAME Tag CRC-16     : 1E9B
```
this is expected because one is for the tag and the other for the combined audio frames 

the question is, how can one re-calc the audio CRC to make sure the audio wasn't altered? can eyeD3 do this?

**Comment by nicfit** [comment]
A brief looks at some very old CRC code leads me so say no, eyeD3 cannot recompute. But like I said, a brief look.

It appears CRC info comes from 1) the LameHeader (as you found) and/or 2) ExtendedTagHeader (optional header in some version of ID3).  There is some checking happening in the LameHeader:
```python
# check the info tag crc. If it's not valid, no point parsing much more.
lamecrc = bin2dec(bytes2bin(frame[190:192]))
if self._crc16(frame[:190]) != lamecrc:
    log.warning("Lame tag  CRC check failed")
else:
    log.debug("Lame tag CRC OK")
```
But it's not checking mp3 data.
