### ISSUE TITLE
tag.clear() + tag.save() fails

### ISSUE THREAD

**Issue by MrHobbits** [nicfit/eyeD3#442]
Small issue,
Using Python3.8, when modifying the tags by clearing them using tag.clear() it removes all the tag data including the tag.file_info.name, which subsequently prevents you from doing a tag.save() without specifying the filename.

In order to resolve this, we have to first save the filename (fname = audio.tag.file_info.name) and then doing audio.tag.save(fname)

With this being said, after you do a clear because it deletes the attributes of file_info, I have not found the way to put the attributes back on to file_info (attributes like  file_info.name). I noticed when doing help(audio.tag.save) the help function says that if 'filename' is not given that it will use the value from file_info. If it clears that data it will throw the exception.

Could you modify the clear() function so that when it clears the file_info it recreates the attribute structure (and possibly other structures commonly used). If it's recreated, then we can do audio.tag.file_info.name = "/user/mrhobbits/my_song.mp3"
If we try to do that now we get the error "AttributeError: 'NoneType' object has no attribute 'name'

**Comment by nicfit** [comment]
Thanks for reporting. Fixed for next release.
