### ISSUE TITLE
log.warning spams console stderr. No option to suppress.

### ISSUE THREAD

**Issue by hagaiwec** [nicfit/eyeD3#480]
Please allow an option to suppress logs output of package. It spams console with massages like:
```cmd
Lame tag CRC check failed
Invalid date: <year>
FrameHeader: Illegal Frame ID: b'CM1 '
EOB frame does not contain a valid mime type
GEOB frame does not contain a mime type
TDRL frame being dropped due to conversion to v1.1
Invalid numeric genre ID: 255
```
and so on.
Frankly, I don't really care if this tests and checks output error, the code still works.
I just want to suppress this logging to stderr.

Thank you

**Comment by nicfit** [comment]
`eyeD3 -l critical` ?
