### ISSUE TITLE
Fixing lame tag CRC

### ISSUE THREAD

**Issue by raymondwanyoike** [nicfit/eyed3#5]
I'm getting a warning while performing eyed3 operations: `eyed3.mp3.headers:WARNING: Lame tag CRC check failed`. Is there a way to fix such files using eyed3?

**Comment by nicfit** [comment]
eyeD3 does not handle the fixes, but may be able to .. the infrastructure is there. Patches welcome, for I don't have plans for this.

**Comment by bicepjai** [comment]
is ther a fix for it now ?

**Comment by nicfit** [comment]
> is ther a fix for it now ?

Not yet.

**Comment by kjesso** [comment]
I was getting the same error "eyed3.mp3.headers:WARNING: Lame tag CRC check failed" when trying to capture specific data from the output of the eyed3 command in a variable within a bash script:

`DISCNUMBER=$(eyed3 --no-color "$MP3" | grep "^disc:" | sed "s/^disc: \([0-9]\).*/\1/")`

As soon as I removed this line from my script the error went way. However, I can keep this line by fixing it to the following:

`DISCNUMBER=$(eyed3 --no-color "$MP3" 2>&1 | grep "^disc:" | sed "s/^disc: \([0-9]\).*/\1/")`

Now the CRC error is gone.
