### ISSUE TITLE
Q: print constant/variable bitrate encoding type with classic plugin?

### ISSUE THREAD

**Issue by atomGit** [nicfit/eyeD3#525]
it looks like the lame plugin relies on the lame tag to determine the encoding type (VBR, CBR, etc.) but obviously this isn't always present, yet it can be an important bit of info

it would be nice if the classic plugin displayed the encoding type without relying on the lame tag, but i'm not seeing how to do this - the stats plugin seems to do this, but i think this should also be displayed with the classic plug

**Comment by nicfit** [comment]
Classic plugin shows VBR using the '~' character.

```
Time: 05:56	MPEG1, Layer III	[ ~235 kb/s @ 44100 Hz - Joint stereo ]
```
