### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by Chir00** [nicfit/eyeD3#53]
Can someone help me?
i run myscript.py and i got this
WARNING:eyed3.id3.frames:Non ascii url, clearing.
(title of mysong)

your program work fine but i need to know how to remove WARNING message.

thx :)

**Comment by nicfit** [comment]
You can removed that frame once you know its ID.
```
 --remove-frame FID    Remove all frames with the given ID. This option may
                        be specified multiple times.
```
Fixing the frame data to be correct may also be posibile depending on the frame.

**Comment by Chir00** [comment]
@nicfit here is some code in myscript.py (i'm new in python)
import eyed3
audiofile = eyed3.load("My_song.mp3")
print(audiofile.tag.title)

When i run it show me like this
WARNING:eyed3.id3.frames:Non ascii url, clearing.
(title of My_song)

--remove-frame FID it work but i can't add in my python script
what should i do?

Thx :)
