### ISSUE TITLE
No module named 'pylast'

### ISSUE THREAD

**Issue by tomasmueller** [nicfit/eyeD3#536]
I have eyed3 running on ubuntu 20.04. Its version 0.8.10. thats the last version in the ubuntu repo and there is no ppa with an newer version. All i want is to tag my music what works fine but i have that error every time eyed3 is running. Installing the module don't solve the problem.

i think the module isn't necessary because eyed3 is tagging all my music but i think slowing down the process. Can i disable that error?

**Comment by nicfit** [comment]
Hi @tomasmueller , 

Please post a stack trace after installing dependencies listed here: https://github.com/nicfit/eyeD3/blob/0.8.x/requirements.txt

Note, the versions. eyeD3 0.8 is older, and may not work with the latest versions of those packages.
