### ISSUE TITLE
Permit milliseconds in ISO8601 timestamp

### ISSUE THREAD

**Issue by joshcvt** [nicfit/eyeD3#547]
Certain audio file generators leave a timestamp in the format
`2021-06-13T00:14:59.000Z`
causing eyeD3 to emit
`Invalid date: 2021-06-13T00:14:59.000Z` on parse

Adding "%Y-%m-%dT%H:%M:%S.%fZ" to permissible parse formats may resolve this issue.

https://github.com/nicfit/eyeD3/blob/daaf6d1cc3bb0153eb968f113b003bd6347957cf/eyed3/core.py#L265

**Comment by nicfit** [comment]
This is not supported by the ID3 specification:  https://github.com/id3/ID3v2.4/blob/master/id3v2.40-structure.txt#L377
