### ISSUE TITLE
Not get fully lyric from mp3 file.

### ISSUE THREAD

**Issue by htm88** [nicfit/eyeD3#548]
I try to get lyric from all file in one folder. Some file are ok, but some file i only recieved the last sentence of lyric.

I run on Python 3.7
My Code 

```python
import eyed3
import os

for root,  dirs, files in os.walk("C:/Users/Hoang/Desktop/1"):
    for file in files:
        try:
            if file.find(".mp3") < 0:
                continue
            path = os.path.abspath(os.path.join(root , file))
            t = eyed3.load(path)
            print("TRACK "+t.tag.title , t.tag.lyrics[0].text)
            #print(t.getArtist())
        except Exception as e:
            print(e)
```

[1.zip](https://github.com/nicfit/eyeD3/files/6683629/1.zip)

I attached zip file with two file: "11_Special Feature-7.mp3" file is ok but "03_News Spotlight News-1.mp3" file is only receive the last sentences "(©Reuters, March 11, 2021)"

Thank you!

**Comment by nicfit** [comment]
03 file only has one line of lyrics, which is actually podcast news info, not really lyrics. The 11 file has newlines in the lyrics text.
