### ISSUE TITLE
'NotImplementedError: Unable to write ID3 v2.2'

### ISSUE THREAD

**Issue by awsms** [nicfit/eyeD3#552]
Having this error when trying to edit a mp3 with id3v2.2 tags.

Related issue: https://github.com/dskrad/mp3chaps/issues/9

**Comment by nicfit** [comment]
ID3 2.2 is read-only. You have to write to v2.3/v2.4

**Comment by rwb196884** [comment]
And how do you do that?

**Comment by danielb2** [comment]
`--to-v2.4`
