### ISSUE TITLE
Doesn't work via file manager context menu

### ISSUE THREAD

**Issue by Sadi58** [nicfit/eyeD3#564]
I have **eyed3** package installed in KDE neon, and it works fine in terminal, but not via file manager (Dolphin) context menu.
I have many user scripts added to my file manager context menu, including those which simply include `for filename in "${@}"; do <SOME_COMMAND+OPTIONS>; done`, using commands like `sort`, `jhead`, `optipng`, `exiftool`, `libreoffice` etc., but I can't do the same with eyeD3, for example like this: `for filename in "${@}"; do eyeD3 --add-image="cover.jpg:FRONT_COVER" "$filename"; done` to add image file named `cover.jpg` in the current directory to the selected mp3 file(s), although terminal command `eyeD3 --add-image "cover.jpg:FRONT_COVER" <FILENAME>` works.

I hope you can implement support for such use or help me find a workaround. Thank you very much.

**Comment by nicfit** [comment]
What is the error this file manager produces?  I can't comment without any clue of what fails.

**Comment by Sadi58** [comment]
Oh, I'm so sorry, I've now seen my mistake: there was a typo in the file name of the script! That's why nothing was happening in the file manager when I clicked on the relevant context menu item. :-(
