### ISSUE TITLE
Please install grako - but it is installed!

### ISSUE THREAD

**Issue by PeterKMcN** [nicfit/eyeD3#572]
Just created new system under Ubuntu 22,04

**installed eyeD3 using sudo pip install**
_sudo pip install eyeD3
Collecting eyeD3
  Using cached eyeD3-0.9.6-py3-none-any.whl (245 kB)
Requirement already satisfied: coverage[toml]<6.0.0,>=5.3.1 in /usr/local/lib/python3.10/dist-packages (from eyeD3) (5.5)
Requirement already satisfied: deprecation<3.0.0,>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from eyeD3) (2.1.0)
Requirement already satisfied: filetype<2.0.0,>=1.0.7 in /usr/local/lib/python3.10/dist-packages (from eyeD3) (1.0.13)
Requirement already satisfied: toml in /usr/local/lib/python3.10/dist-packages (from coverage[toml]<6.0.0,>=5.3.1->eyeD3) (0.10.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from deprecation<3.0.0,>=2.1.0->eyeD3) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->deprecation<3.0.0,>=2.1.0->eyeD3) (2.4.7)
Installing collected packages: eyeD3
Successfully installed eyeD3-0.9.6
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv_

**installed eyeD3[display-plugin] using sudo pip install**
_sudo pip install eyeD3[display-plugin]
Requirement already satisfied: eyeD3[display-plugin] in /usr/local/lib/python3.10/dist-packages (0.9.6)
Requirement already satisfied: filetype<2.0.0,>=1.0.7 in /usr/local/lib/python3.10/dist-packages (from eyeD3[display-plugin]) (1.0.13)
Requirement already satisfied: deprecation<3.0.0,>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from eyeD3[display-plugin]) (2.1.0)
Requirement already satisfied: coverage[toml]<6.0.0,>=5.3.1 in /usr/local/lib/python3.10/dist-packages (from eyeD3[display-plugin]) (5.5)
Requirement already satisfied: grako<4.0.0,>=3.99.9 in /usr/local/lib/python3.10/dist-packages (from eyeD3[display-plugin]) (3.99.9)
Requirement already satisfied: toml in /usr/local/lib/python3.10/dist-packages (from coverage[toml]<6.0.0,>=5.3.1->eyeD3[display-plugin]) (0.10.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from deprecation<3.0.0,>=2.1.0->eyeD3[display-plugin]) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->deprecation<3.0.0,>=2.1.0->eyeD3[display-plugin]) (2.4.7)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv_

**Command: eyeD3 --plugin display -p "%texts%" "test.mp3"
Produces error:** 
_Unknown module 'grako'
Please install grako! E.g. $ pip install grako_

**so tried to install gracko**
_sudo pip install grako
Requirement already satisfied: grako in /usr/local/lib/python3.10/dist-packages (3.99.9)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv_

tried uninstalling and reinstalling gracko - same result

tried uninstalling and reinstalling eyed3 - same result

tried uninstalling and reinstalling eyed3 forcing no cache - same result

tried installing as user and as root

Any help welcome

**Comment by marcelpaulo** [comment]
Xubuntu 22.04, installing as user:

`pip3 install --user eyeD3[display-plugin]`

same error here.

**Comment by nicfit** [comment]
The display plugin is installed as a eyeD3 "extra".. e.g. `pip install eyeD3[display-plugin]` and did work last I check, but this plugin is being dropped here: https://github.com/nicfit/eyeD3/pull/585.  So it will be gone on the next 0.9 version of eyeD3.

Display plugin is really powerful, but it was a contribution and requires a maintainer. The grako project is also no longer maintained, and python versions have outpaced it.
