### ISSUE TITLE
How to write custom tags?

### ISSUE THREAD

**Issue by foremtehan** [nicfit/eyeD3#579]
Hi there, Can you teach me how to write custom tags ? which argument should i pass ?

I want to include `Credits` tag but i'll get the following error:

`eyeD3: error: unrecognized arguments: --credits`

**Comment by frsconsulting** [comment]
If the tag has a native ID3 frame such as `TMCL` (the [ID3 v2.4](https://id3.org/id3v2.4.0-frames) frame for musician credits), you can add it via `--text-frame TMCL:'Saxophone:Zoot;Trumpet:Lips;Drums:Animal'`

For custom tags which don't have a native ID3 frame, add a user text frame: `--user-text-frame CREDITS:'Dr. Teeth (Keyboards and Vocals)'`
