### ISSUE TITLE
write into FLAC files via cli

### ISSUE THREAD

**Issue by foremtehan** [nicfit/eyeD3#580]
I use eyeD3 cli to write tags, But looks like it only working for mp3 files

`eyeD3 --artist "My Artist" 01 A Million Miles Away.flac`

I won't get any error but tags never written. same for m4a files.

**Comment by nicfit** [comment]
eyeD3 requires understanding FLAC and m4a audio formats for this.  Duplicate of https://github.com/nicfit/eyeD3/issues/404
