### ISSUE TITLE
Cannot add mood

### ISSUE THREAD

**Issue by ScribbleGhost** [nicfit/eyeD3#582]
This is a fantastic module. Thanks! 😁

How can I add a mood `TMOO` using the python module?

I couldn't find it in the docs. And I have been struggling with this for a while. 😥

**Comment by nicfit** [comment]
Hello @ScribbleGhost , eyeD3 has a generic option for tags that are not "common".  This works for me:
```
eyeD3 --text-frame TMOO:Happy ./test.mp3
```

**Comment by ScribbleGhost** [comment]
Thanks. I ended up using the mutagen library instead. Also, that code is just for the CLI, right? I am using a Python script.
