### ISSUE TITLE
Remove all tags

### ISSUE THREAD

**Issue by amir5485** [nicfit/eyeD3#596]
Hi, how to remove all tags from mp3 file?

================================
import eyed3

audiofile = eyed3.load("song.mp3")
audiofile.tag.remove(all())
audiofile.tag.artist = "Token Entry"
audiofile.tag.album = "Free For All Comp LP"

audiofile.tag.save()

**Comment by optio50** [comment]
https://eyed3.readthedocs.io/en/latest/eyed3.id3.html#module-eyed3.id3.tag

Looks like clear might work
