### ISSUE TITLE
Invalid frame-id COMM for text frame

### ISSUE THREAD

**Issue by foremtehan** [nicfit/eyeD3#598]
I want to add comment tag by frame id which is `COMM` like below:

```
eyeD3 --text-frame COMM:'my-comment' file.mp3
```

But i get the following error:

```
Setting b'COMM' text frame to 'my-comment'
Invalid frame-id for text frame
```

What's wrong? this frame id is standard.

**Comment by nicfit** [comment]
See `--add-comment`, text frames in ID3 begin with `T`.
