### ISSUE TITLE
read/writing tags from/to mp3 with no metadata raises an error

### ISSUE THREAD

**Issue by JGTB0PL** [nicfit/eyeD3#600]
similar to #36
eyeD3 version: 0.9.7
Operating System: Microsoft Windows [Version 10.0.19045.2846]

[example.mp3](https://drive.google.com/file/d/19uTH_RrtEx2167b1QaJ0AdKSEmdqofSc/view?usp=sharing)

the example.mp3 has no metadata
so
```python
audiofile = eyed3.load(r"example.mp3")
audiofile.tag.track_num = 1
audiofile.tag.save()
```
raises an error
`AttributeError: 'NoneType' object has no attribute 'track_num'`

changing 161st line in mp3\\\_\_init\_\_.py
from `self._tag = None` to `self._tag = id3.Tag()`
seems to "fix" the issue

but now a slight modification of the main python program is required to avoid the `eyed3.id3.tag.TagException: No file` error
```python
audiofile = eyed3.load(r"example.mp3")
audiofile.tag.track_num = 1
audiofile.tag.save(r"example.mp3")
```

the fix is only a really bad bodge so I didn't feel the need to make a pull request

**Comment by nicfit** [comment]
tag is None to communicate the fact that there is no tag, often useful to know.

Adjusting your example code:

```python
audiofile = eyed3.load(r"example.mp3")
if audile.tag is None:
    audiofile.initTag(...)    
audiofile.tag.track_num = 1
audiofile.tag.save()
```
