### ISSUE TITLE
How to get/set ID3v2 Tags?

### ISSUE THREAD

**Issue by YuganshT79** [nicfit/eyeD3#62]
so I have used eyed3 for editing tags for my media but they doesn't update on my windows media player , so is there a way to show them in Windows media player?

**Comment by nicfit** [comment]
Not sure, I don't test on (or have) Windows.

**Comment by nicfit** [comment]
Hi @CoderYugansh , it seems that Windows Explorer MUST have old ID3 v1.x tags, so you should save your files with both a v1 and v2 tags. I found this issue in the old BitBucket repo..

https://bitbucket.org/nicfit/eyed3/issues/22/tag-save-method-does-not-apply-changes

**Comment by nium9** [comment]
Hi,

The link given is not working.
i was wondering if an alternative.
