### ISSUE TITLE
Uncaught exception: Unable to write ID3 v2.2

### ISSUE THREAD

**Issue by WGroleau** [nicfit/eyeD3#620]
Command used:
`eyeD3 -d 1 -D 1 (path)/*`

Some files had v2.2, some 2.3, some 2.4

I don't know which file had the error, but the results ended with
`Uncaught exception: Unable to write ID3 v2.2`
and a stack trace.

I cannot provide the stack trace because I cleared the terminal display in the process of updating the files individually (changing all to v2.4 and other updates)

**Comment by WGroleau** [comment]
One way I recently reproduced this is in a track that had ID3 v2.2, I tried to change an ASCII apostrophe to U+2019 in the track title.

After I applied --encoding utf8 --to-v2.4 to the file, the change did not raise an error.  The encoding should not have been needed, as my locale is set to en_US.UTF-8

**Comment by nicfit** [comment]
2.2 is read-only.
