### ISSUE TITLE
Not installing correctly on MacOS?

### ISSUE THREAD

**Issue by sfenwick** [nicfit/eyeD3#624]
I'm struggling to get this installed correctly on MacOS 10.14 (Mojave), not using Homebrew.

Running "pip3 install eyeD3" gave this result:

> Collecting eyeD3
>   Downloading eyed3-0.9.7-py3-none-any.whl.metadata (6.0 kB)
> Collecting coverage<6.0.0,>=5.3.1 (from coverage[toml]<6.0.0,>=5.3.1->eyeD3)
>   Downloading coverage-5.5.tar.gz (691 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 691.3/691.3 kB 5.1 MB/s eta 0:00:00
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Installing backend dependencies ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting deprecation<3.0.0,>=2.1.0 (from eyeD3)
>   Downloading deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
> Collecting filetype<2.0.0,>=1.0.7 (from eyeD3)
>   Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
> Collecting toml (from coverage[toml]<6.0.0,>=5.3.1->eyeD3)
>   Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
> Collecting packaging (from deprecation<3.0.0,>=2.1.0->eyeD3)
>   Downloading packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
> Downloading eyed3-0.9.7-py3-none-any.whl (246 kB)
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.1/246.1 kB 8.4 MB/s eta 0:00:00
> Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
> Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
> Downloading packaging-24.0-py3-none-any.whl (53 kB)
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 kB 1.9 MB/s eta 0:00:00
> Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
> Building wheels for collected packages: coverage
>   Building wheel for coverage (pyproject.toml) ... done
>   Created wheel for coverage: filename=coverage-5.5-py3-none-any.whl size=199987 sha256=04d448e1b451c991e7a24a1be897267d1148163ccc7e7eac495f440b5b62371e
>   Stored in directory: /Users/scf/Library/Caches/pip/wheels/6a/bd/bb/78a1f089b77ae22690955a85424d9d47da271b955d61954e0a
> Successfully built coverage
> Installing collected packages: filetype, toml, packaging, coverage, deprecation, eyeD3
> Successfully installed coverage-5.5 deprecation-2.1.0 eyeD3-0.9.7 filetype-1.2.0 packaging-24.0 toml-0.10.2

which all looks correct. But then when I try to use "import eyeD3" in a python3 script I get:

> Media-Server:Music scf$ python3 ~/pylist.py
> Traceback (most recent call last):
>   File "/Users/scf/pylist.py", line 4, in <module>
>     import eyeD3
> ModuleNotFoundError: No module named 'eyeD3'

Trying to execute "eyeD3" from any Terminal prompt gives:
> Media-Server:Music scf$ python3 eyeD3
/Library/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python: can't open file '/Volumes/Music 1TB Ashland/iTunes/Music/eyeD3': [Errno 2] No such file or directory

Any help here? Thanks!

**Comment by nicfit** [comment]
Module name to import is `eyed3`.  There should a script called `eyeD3` installed, so the way to invoke the CLI is `eyeD3 ...`
