### ISSUE TITLE
How to clear the disc number when it has a value of "01/02"

### ISSUE THREAD

**Issue by morfikov** [nicfit/eyeD3#626]
Some of my songs have weird disc number values, for instance `01/02` suggesting that there are two discs and this one is the first one (instead of the usual `01` or `1` ). I wanted to clear this info out by using `--disc-num="0"` . This works well with the field when there's just a number like `01` or `1`, but it doesn't work with this `01/02` -- it only clears the first number, so it becomes `00/02`. Is there a way to remove the value altogether?

**Comment by WhitePeter** [comment]
Depending on what you want to achieve, you need to either clear the [TPOS](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html#tpos) text frame:
```
# mind the colon
eyeD3 --text-frame=TPOS: <files>
# equivalent approach
eyeD3 --disc-num=0 --disc-total=0 <files>
```
or just set it, e.g.:
```
eyeD3 --text-frame=TPOS:<disc-num> <files>
# equivalent
eyeD3 --disc-num=<disc-num> --disc-total=0 <files>
# -> disc: <disc-num>

# or as a part of a set of 1 members
eyeD3 --text-frame=TPOS:<disc-num>/<disc-total> <files>
# equivalent
eyeD3 --disc-num=<disc-num> --disc-total=<disc-total> <files>
# -> disc: <disc-num>/<disc-total>
```
