### ISSUE TITLE
Writing lyrics file containing LATIN1 text failed

### ISSUE THREAD

**Issue by Wasnix** [nicfit/eyeD3#75]
Writing lyrics failed when lyrics file contains LATIN1 song text with special chars.

eyeD3 --encoding latin1 --to-v2.3 --add-lyrics /tmp/lyrics.txt song.mp3

eyeD3: error: argument --add-lyrics: invalid LyricsArg value: '/tmp/lyrics.txt'

Recoding file /tmp/lyrics.txt from LATIN1 to UTF-8 and repeating same command from above now workes. ID3v2.3 standard should support writing LATIN1 lyrics.

I'm using latest Debian Linux (buster) with eyed3 08-1

**Comment by nicfit** [comment]
Not all character can be encoded using latin1, if you omit ``--encoding latin1`` it also would work.
