### ISSUE TITLE
Not always finding tags.

### ISSUE THREAD

**Issue by programmin1** [nicfit/eyed3#8]
Eyed3 is quite handy, but unfortunately doesn't always find the tag data. For example, go to http://new.toonighcog.org/sermons/ and download "December 6, 2015 PM Service", try:

```
myinfo = eyed3.load( file )
print myinfo.tag.frame_set
```

You'll get: AttributeError: 'NoneType' object has no attribute 'frame_set'

**Comment by nicfit** [comment]
I downloaded the file and opened with a hex editor, the file does not contain a tag. eyeD3 is correct in this case.
