### ISSUE TITLE
CPU loop on import (Python 2.7.8 on Windows 10)

### ISSUE THREAD

**Issue by codingatty** [nicfit/eyeD3#84]
I updated today from eyeD3 0.6.18 to 0.8.1. eyeD3 now loops on import. The script is non-responsive, even to a CTRL-C; Process Explorer sees CPU to the python task go to nearly 25% (i.e., one core).

Script to reproduce:
```Python
import sys
print "OS info:\n ", sys.getwindowsversion()
print "Python info:\n ", sys.version
print "about to import"
import eyeD3
print "import completed"
```

Output:
```
OS info:
  sys.getwindowsversion(major=6, minor=2, build=9200, platform=2, service_pack='')
Python info:
  2.7.8 (default, Jul  2 2014, 19:50:44) [MSC v.1500 32 bit (Intel)]
about to import
```
at which point it hangs, the import never completing. I can kill the Python task from Process Explorer.

I have not yet delved into the eyeD3 code. I'll try to do that over the weekend. I first wanted to check if this is known (I searched the existing issues and didn't see any likely candidates).

**Comment by nicfit** [comment]
The module name if  ``eyed3`` for version >=0.7, while the CLI is ``eyeD3``. How are things if you ``import eyed3``?

**Comment by codingatty** [comment]
Initially an import error ("ImportError: No module named eyed3"); after reinstall, same loop.

Since I installed 0.8.1 over the existing 0.6.18, the existing directory was named "eyeD3", even after the 0.8.1 install. I deleted it and reinstalled (pip install eyed3), and now get the same loop.

(Note; distinfo directory is still named "eyeD3-0.8.1.dist-info" with the upper-case D if that matters.)

**Comment by nicfit** [comment]
Nah, eyeD3 is the project name, the module name is just lower-cased per pep8 style.  Sounds like your install is horked, have you tried installing with pip?

**Comment by codingatty** [comment]
Yup, I installed with pip the first time and reinstalled, again with pip. Same result. I have also tried it on another machine running Python 2.7.8 and Windows 7 (rather than Windows 10). Same result.

I'll try hacking on it a bit and see if I can narrow it down.

**Comment by codingatty** [comment]
It looks like the problem is in magic, not eyed3. I've isolated it to this statement in eyed3/utils/__init__.py:

```
        magic.Magic.__init__(self, mime=True, mime_encoding=False,
                             keep_going=False)
```

I tried magic directly with:

```
import magic
mymagic = magic.Magic()
```

and it hangs in magic/__init__.py, just at the 
```
self.cookie = magic_open(self.flags)
```
statement. Sounds like not your problem.
