### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by birdmw** [nicfit/eyeD3#91]
Tried everything man. This error is persistant. setup tools install doesn't help. pip install -r requirements/test.txt $ pip install -r requirements/dev.txt doesn't help. Fresh install of anaconda2 and pycharm doesnt even help..

**Comment by pettazz** [comment]
You need to install libmagic.

OS X: ````brew install libmagic````
Ubuntu: ````apt-get install libmagic````

**Comment by exixx** [comment]
I've got the same issue, and there's a question on stack that looks like a couple other people have it as well. Installation returns normally but an import or command line use returns a callback indicating that libmagic is not installed, but it is installed. Using python 3.5.4

**Comment by nicfit** [comment]
libmagic is required for the time being. Thanks to @pettazz, you have some instructions.
